// THIS FILE IS AUTOGENERATED BY wb_intercon_gen
// ANY MANUAL CHANGES WILL BE LOST
module wb_intercon
   (input         wb_clk_i,
    input         wb_rst_i,
    input  [31:0] wb_or1k_i_adr_i,
    input  [31:0] wb_or1k_i_dat_i,
    input   [3:0] wb_or1k_i_sel_i,
    input         wb_or1k_i_we_i,
    input         wb_or1k_i_cyc_i,
    input         wb_or1k_i_stb_i,
    input   [2:0] wb_or1k_i_cti_i,
    input   [1:0] wb_or1k_i_bte_i,
    output [31:0] wb_or1k_i_dat_o,
    output        wb_or1k_i_ack_o,
    output        wb_or1k_i_err_o,
    output        wb_or1k_i_rty_o,
    input  [31:0] wb_or1k_d_adr_i,
    input  [31:0] wb_or1k_d_dat_i,
    input   [3:0] wb_or1k_d_sel_i,
    input         wb_or1k_d_we_i,
    input         wb_or1k_d_cyc_i,
    input         wb_or1k_d_stb_i,
    input   [2:0] wb_or1k_d_cti_i,
    input   [1:0] wb_or1k_d_bte_i,
    output [31:0] wb_or1k_d_dat_o,
    output        wb_or1k_d_ack_o,
    output        wb_or1k_d_err_o,
    output        wb_or1k_d_rty_o,
    input  [31:0] wb_dbg_adr_i,
    input  [31:0] wb_dbg_dat_i,
    input   [3:0] wb_dbg_sel_i,
    input         wb_dbg_we_i,
    input         wb_dbg_cyc_i,
    input         wb_dbg_stb_i,
    input   [2:0] wb_dbg_cti_i,
    input   [1:0] wb_dbg_bte_i,
    output [31:0] wb_dbg_dat_o,
    output        wb_dbg_ack_o,
    output        wb_dbg_err_o,
    output        wb_dbg_rty_o,
    input  [31:0] wb_dbg_rs232_adr_i,
    input  [31:0] wb_dbg_rs232_dat_i,
    input   [3:0] wb_dbg_rs232_sel_i,
    input         wb_dbg_rs232_we_i,
    input         wb_dbg_rs232_cyc_i,
    input         wb_dbg_rs232_stb_i,
    input   [2:0] wb_dbg_rs232_cti_i,
    input   [1:0] wb_dbg_rs232_bte_i,
    output [31:0] wb_dbg_rs232_dat_o,
    output        wb_dbg_rs232_ack_o,
    output        wb_dbg_rs232_err_o,
    output        wb_dbg_rs232_rty_o,
    output [31:0] wb_ddr2_adr_o,
    output [31:0] wb_ddr2_dat_o,
    output  [3:0] wb_ddr2_sel_o,
    output        wb_ddr2_we_o,
    output        wb_ddr2_cyc_o,
    output        wb_ddr2_stb_o,
    output  [2:0] wb_ddr2_cti_o,
    output  [1:0] wb_ddr2_bte_o,
    input  [31:0] wb_ddr2_dat_i,
    input         wb_ddr2_ack_i,
    input         wb_ddr2_err_i,
    input         wb_ddr2_rty_i,
    output [31:0] wb_uart0_adr_o,
    output  [7:0] wb_uart0_dat_o,
    output  [3:0] wb_uart0_sel_o,
    output        wb_uart0_we_o,
    output        wb_uart0_cyc_o,
    output        wb_uart0_stb_o,
    output  [2:0] wb_uart0_cti_o,
    output  [1:0] wb_uart0_bte_o,
    input   [7:0] wb_uart0_dat_i,
    input         wb_uart0_ack_i,
    input         wb_uart0_err_i,
    input         wb_uart0_rty_i,
    output [31:0] wb_gpio_sw_adr_o,
    output [15:0] wb_gpio_sw_dat_o,
    output  [3:0] wb_gpio_sw_sel_o,
    output        wb_gpio_sw_we_o,
    output        wb_gpio_sw_cyc_o,
    output        wb_gpio_sw_stb_o,
    output  [2:0] wb_gpio_sw_cti_o,
    output  [1:0] wb_gpio_sw_bte_o,
    input  [15:0] wb_gpio_sw_dat_i,
    input         wb_gpio_sw_ack_i,
    input         wb_gpio_sw_err_i,
    input         wb_gpio_sw_rty_i,
    output [31:0] wb_gpio_pbtn_adr_o,
    output  [4:0] wb_gpio_pbtn_dat_o,
    output  [3:0] wb_gpio_pbtn_sel_o,
    output        wb_gpio_pbtn_we_o,
    output        wb_gpio_pbtn_cyc_o,
    output        wb_gpio_pbtn_stb_o,
    output  [2:0] wb_gpio_pbtn_cti_o,
    output  [1:0] wb_gpio_pbtn_bte_o,
    input   [4:0] wb_gpio_pbtn_dat_i,
    input         wb_gpio_pbtn_ack_i,
    input         wb_gpio_pbtn_err_i,
    input         wb_gpio_pbtn_rty_i,
    output [31:0] wb_gpio_led_adr_o,
    output [15:0] wb_gpio_led_dat_o,
    output  [3:0] wb_gpio_led_sel_o,
    output        wb_gpio_led_we_o,
    output        wb_gpio_led_cyc_o,
    output        wb_gpio_led_stb_o,
    output  [2:0] wb_gpio_led_cti_o,
    output  [1:0] wb_gpio_led_bte_o,
    input  [15:0] wb_gpio_led_dat_i,
    input         wb_gpio_led_ack_i,
    input         wb_gpio_led_err_i,
    input         wb_gpio_led_rty_i,
    output [31:0] wb_gpio_pmod_adr_o,
    output [31:0] wb_gpio_pmod_dat_o,
    output  [3:0] wb_gpio_pmod_sel_o,
    output        wb_gpio_pmod_we_o,
    output        wb_gpio_pmod_cyc_o,
    output        wb_gpio_pmod_stb_o,
    output  [2:0] wb_gpio_pmod_cti_o,
    output  [1:0] wb_gpio_pmod_bte_o,
    input  [31:0] wb_gpio_pmod_dat_i,
    input         wb_gpio_pmod_ack_i,
    input         wb_gpio_pmod_err_i,
    input         wb_gpio_pmod_rty_i,
    output [31:0] wb_sseg_ctrl_adr_o,
    output [15:0] wb_sseg_ctrl_dat_o,
    output  [3:0] wb_sseg_ctrl_sel_o,
    output        wb_sseg_ctrl_we_o,
    output        wb_sseg_ctrl_cyc_o,
    output        wb_sseg_ctrl_stb_o,
    output  [2:0] wb_sseg_ctrl_cti_o,
    output  [1:0] wb_sseg_ctrl_bte_o,
    input  [15:0] wb_sseg_ctrl_dat_i,
    input         wb_sseg_ctrl_ack_i,
    input         wb_sseg_ctrl_err_i,
    input         wb_sseg_ctrl_rty_i,
    output [31:0] wb_rgb_led_adr_o,
    output [23:0] wb_rgb_led_dat_o,
    output  [3:0] wb_rgb_led_sel_o,
    output        wb_rgb_led_we_o,
    output        wb_rgb_led_cyc_o,
    output        wb_rgb_led_stb_o,
    output  [2:0] wb_rgb_led_cti_o,
    output  [1:0] wb_rgb_led_bte_o,
    input  [23:0] wb_rgb_led_dat_i,
    input         wb_rgb_led_ack_i,
    input         wb_rgb_led_err_i,
    input         wb_rgb_led_rty_i,
    output [31:0] wb_ps2_0_adr_o,
    output  [7:0] wb_ps2_0_dat_o,
    output  [3:0] wb_ps2_0_sel_o,
    output        wb_ps2_0_we_o,
    output        wb_ps2_0_cyc_o,
    output        wb_ps2_0_stb_o,
    output  [2:0] wb_ps2_0_cti_o,
    output  [1:0] wb_ps2_0_bte_o,
    input   [7:0] wb_ps2_0_dat_i,
    input         wb_ps2_0_ack_i,
    input         wb_ps2_0_err_i,
    input         wb_ps2_0_rty_i,
    output [31:0] wb_xadc0_adr_o,
    output [15:0] wb_xadc0_dat_o,
    output  [3:0] wb_xadc0_sel_o,
    output        wb_xadc0_we_o,
    output        wb_xadc0_cyc_o,
    output        wb_xadc0_stb_o,
    output  [2:0] wb_xadc0_cti_o,
    output  [1:0] wb_xadc0_bte_o,
    input  [15:0] wb_xadc0_dat_i,
    input         wb_xadc0_ack_i,
    input         wb_xadc0_err_i,
    input         wb_xadc0_rty_i,
    output [31:0] wb_ddr2_cfg0_adr_o,
    output [15:0] wb_ddr2_cfg0_dat_o,
    output  [3:0] wb_ddr2_cfg0_sel_o,
    output        wb_ddr2_cfg0_we_o,
    output        wb_ddr2_cfg0_cyc_o,
    output        wb_ddr2_cfg0_stb_o,
    output  [2:0] wb_ddr2_cfg0_cti_o,
    output  [1:0] wb_ddr2_cfg0_bte_o,
    input  [15:0] wb_ddr2_cfg0_dat_i,
    input         wb_ddr2_cfg0_ack_i,
    input         wb_ddr2_cfg0_err_i,
    input         wb_ddr2_cfg0_rty_i,
    output [31:0] wb_spi_flash_adr_o,
    output  [7:0] wb_spi_flash_dat_o,
    output  [3:0] wb_spi_flash_sel_o,
    output        wb_spi_flash_we_o,
    output        wb_spi_flash_cyc_o,
    output        wb_spi_flash_stb_o,
    output  [2:0] wb_spi_flash_cti_o,
    output  [1:0] wb_spi_flash_bte_o,
    input   [7:0] wb_spi_flash_dat_i,
    input         wb_spi_flash_ack_i,
    input         wb_spi_flash_err_i,
    input         wb_spi_flash_rty_i,
    output [31:0] wb_spi_accel_adr_o,
    output  [7:0] wb_spi_accel_dat_o,
    output  [3:0] wb_spi_accel_sel_o,
    output        wb_spi_accel_we_o,
    output        wb_spi_accel_cyc_o,
    output        wb_spi_accel_stb_o,
    output  [2:0] wb_spi_accel_cti_o,
    output  [1:0] wb_spi_accel_bte_o,
    input   [7:0] wb_spi_accel_dat_i,
    input         wb_spi_accel_ack_i,
    input         wb_spi_accel_err_i,
    input         wb_spi_accel_rty_i,
    output [31:0] wb_i2c_temp_adr_o,
    output  [7:0] wb_i2c_temp_dat_o,
    output  [3:0] wb_i2c_temp_sel_o,
    output        wb_i2c_temp_we_o,
    output        wb_i2c_temp_cyc_o,
    output        wb_i2c_temp_stb_o,
    output  [2:0] wb_i2c_temp_cti_o,
    output  [1:0] wb_i2c_temp_bte_o,
    input   [7:0] wb_i2c_temp_dat_i,
    input         wb_i2c_temp_ack_i,
    input         wb_i2c_temp_err_i,
    input         wb_i2c_temp_rty_i,
    output [31:0] wb_rom0_adr_o,
    output [31:0] wb_rom0_dat_o,
    output  [3:0] wb_rom0_sel_o,
    output        wb_rom0_we_o,
    output        wb_rom0_cyc_o,
    output        wb_rom0_stb_o,
    output  [2:0] wb_rom0_cti_o,
    output  [1:0] wb_rom0_bte_o,
    input  [31:0] wb_rom0_dat_i,
    input         wb_rom0_ack_i,
    input         wb_rom0_err_i,
    input         wb_rom0_rty_i);

wire [31:0] wb_m2s_or1k_i_ddr2_adr;
wire [31:0] wb_m2s_or1k_i_ddr2_dat;
wire  [3:0] wb_m2s_or1k_i_ddr2_sel;
wire        wb_m2s_or1k_i_ddr2_we;
wire        wb_m2s_or1k_i_ddr2_cyc;
wire        wb_m2s_or1k_i_ddr2_stb;
wire  [2:0] wb_m2s_or1k_i_ddr2_cti;
wire  [1:0] wb_m2s_or1k_i_ddr2_bte;
wire [31:0] wb_s2m_or1k_i_ddr2_dat;
wire        wb_s2m_or1k_i_ddr2_ack;
wire        wb_s2m_or1k_i_ddr2_err;
wire        wb_s2m_or1k_i_ddr2_rty;
wire [31:0] wb_m2s_or1k_i_rom0_adr;
wire [31:0] wb_m2s_or1k_i_rom0_dat;
wire  [3:0] wb_m2s_or1k_i_rom0_sel;
wire        wb_m2s_or1k_i_rom0_we;
wire        wb_m2s_or1k_i_rom0_cyc;
wire        wb_m2s_or1k_i_rom0_stb;
wire  [2:0] wb_m2s_or1k_i_rom0_cti;
wire  [1:0] wb_m2s_or1k_i_rom0_bte;
wire [31:0] wb_s2m_or1k_i_rom0_dat;
wire        wb_s2m_or1k_i_rom0_ack;
wire        wb_s2m_or1k_i_rom0_err;
wire        wb_s2m_or1k_i_rom0_rty;
wire [31:0] wb_m2s_or1k_d_ddr2_adr;
wire [31:0] wb_m2s_or1k_d_ddr2_dat;
wire  [3:0] wb_m2s_or1k_d_ddr2_sel;
wire        wb_m2s_or1k_d_ddr2_we;
wire        wb_m2s_or1k_d_ddr2_cyc;
wire        wb_m2s_or1k_d_ddr2_stb;
wire  [2:0] wb_m2s_or1k_d_ddr2_cti;
wire  [1:0] wb_m2s_or1k_d_ddr2_bte;
wire [31:0] wb_s2m_or1k_d_ddr2_dat;
wire        wb_s2m_or1k_d_ddr2_ack;
wire        wb_s2m_or1k_d_ddr2_err;
wire        wb_s2m_or1k_d_ddr2_rty;
wire [31:0] wb_m2s_or1k_d_uart0_adr;
wire [31:0] wb_m2s_or1k_d_uart0_dat;
wire  [3:0] wb_m2s_or1k_d_uart0_sel;
wire        wb_m2s_or1k_d_uart0_we;
wire        wb_m2s_or1k_d_uart0_cyc;
wire        wb_m2s_or1k_d_uart0_stb;
wire  [2:0] wb_m2s_or1k_d_uart0_cti;
wire  [1:0] wb_m2s_or1k_d_uart0_bte;
wire [31:0] wb_s2m_or1k_d_uart0_dat;
wire        wb_s2m_or1k_d_uart0_ack;
wire        wb_s2m_or1k_d_uart0_err;
wire        wb_s2m_or1k_d_uart0_rty;
wire [31:0] wb_m2s_or1k_d_gpio_sw_adr;
wire [31:0] wb_m2s_or1k_d_gpio_sw_dat;
wire  [3:0] wb_m2s_or1k_d_gpio_sw_sel;
wire        wb_m2s_or1k_d_gpio_sw_we;
wire        wb_m2s_or1k_d_gpio_sw_cyc;
wire        wb_m2s_or1k_d_gpio_sw_stb;
wire  [2:0] wb_m2s_or1k_d_gpio_sw_cti;
wire  [1:0] wb_m2s_or1k_d_gpio_sw_bte;
wire [31:0] wb_s2m_or1k_d_gpio_sw_dat;
wire        wb_s2m_or1k_d_gpio_sw_ack;
wire        wb_s2m_or1k_d_gpio_sw_err;
wire        wb_s2m_or1k_d_gpio_sw_rty;
wire [31:0] wb_m2s_or1k_d_gpio_pbtn_adr;
wire [31:0] wb_m2s_or1k_d_gpio_pbtn_dat;
wire  [3:0] wb_m2s_or1k_d_gpio_pbtn_sel;
wire        wb_m2s_or1k_d_gpio_pbtn_we;
wire        wb_m2s_or1k_d_gpio_pbtn_cyc;
wire        wb_m2s_or1k_d_gpio_pbtn_stb;
wire  [2:0] wb_m2s_or1k_d_gpio_pbtn_cti;
wire  [1:0] wb_m2s_or1k_d_gpio_pbtn_bte;
wire [31:0] wb_s2m_or1k_d_gpio_pbtn_dat;
wire        wb_s2m_or1k_d_gpio_pbtn_ack;
wire        wb_s2m_or1k_d_gpio_pbtn_err;
wire        wb_s2m_or1k_d_gpio_pbtn_rty;
wire [31:0] wb_m2s_or1k_d_gpio_led_adr;
wire [31:0] wb_m2s_or1k_d_gpio_led_dat;
wire  [3:0] wb_m2s_or1k_d_gpio_led_sel;
wire        wb_m2s_or1k_d_gpio_led_we;
wire        wb_m2s_or1k_d_gpio_led_cyc;
wire        wb_m2s_or1k_d_gpio_led_stb;
wire  [2:0] wb_m2s_or1k_d_gpio_led_cti;
wire  [1:0] wb_m2s_or1k_d_gpio_led_bte;
wire [31:0] wb_s2m_or1k_d_gpio_led_dat;
wire        wb_s2m_or1k_d_gpio_led_ack;
wire        wb_s2m_or1k_d_gpio_led_err;
wire        wb_s2m_or1k_d_gpio_led_rty;
wire [31:0] wb_m2s_or1k_d_gpio_pmod_adr;
wire [31:0] wb_m2s_or1k_d_gpio_pmod_dat;
wire  [3:0] wb_m2s_or1k_d_gpio_pmod_sel;
wire        wb_m2s_or1k_d_gpio_pmod_we;
wire        wb_m2s_or1k_d_gpio_pmod_cyc;
wire        wb_m2s_or1k_d_gpio_pmod_stb;
wire  [2:0] wb_m2s_or1k_d_gpio_pmod_cti;
wire  [1:0] wb_m2s_or1k_d_gpio_pmod_bte;
wire [31:0] wb_s2m_or1k_d_gpio_pmod_dat;
wire        wb_s2m_or1k_d_gpio_pmod_ack;
wire        wb_s2m_or1k_d_gpio_pmod_err;
wire        wb_s2m_or1k_d_gpio_pmod_rty;
wire [31:0] wb_m2s_or1k_d_sseg_ctrl_adr;
wire [31:0] wb_m2s_or1k_d_sseg_ctrl_dat;
wire  [3:0] wb_m2s_or1k_d_sseg_ctrl_sel;
wire        wb_m2s_or1k_d_sseg_ctrl_we;
wire        wb_m2s_or1k_d_sseg_ctrl_cyc;
wire        wb_m2s_or1k_d_sseg_ctrl_stb;
wire  [2:0] wb_m2s_or1k_d_sseg_ctrl_cti;
wire  [1:0] wb_m2s_or1k_d_sseg_ctrl_bte;
wire [31:0] wb_s2m_or1k_d_sseg_ctrl_dat;
wire        wb_s2m_or1k_d_sseg_ctrl_ack;
wire        wb_s2m_or1k_d_sseg_ctrl_err;
wire        wb_s2m_or1k_d_sseg_ctrl_rty;
wire [31:0] wb_m2s_or1k_d_rgb_led_adr;
wire [31:0] wb_m2s_or1k_d_rgb_led_dat;
wire  [3:0] wb_m2s_or1k_d_rgb_led_sel;
wire        wb_m2s_or1k_d_rgb_led_we;
wire        wb_m2s_or1k_d_rgb_led_cyc;
wire        wb_m2s_or1k_d_rgb_led_stb;
wire  [2:0] wb_m2s_or1k_d_rgb_led_cti;
wire  [1:0] wb_m2s_or1k_d_rgb_led_bte;
wire [31:0] wb_s2m_or1k_d_rgb_led_dat;
wire        wb_s2m_or1k_d_rgb_led_ack;
wire        wb_s2m_or1k_d_rgb_led_err;
wire        wb_s2m_or1k_d_rgb_led_rty;
wire [31:0] wb_m2s_or1k_d_ps2_0_adr;
wire [31:0] wb_m2s_or1k_d_ps2_0_dat;
wire  [3:0] wb_m2s_or1k_d_ps2_0_sel;
wire        wb_m2s_or1k_d_ps2_0_we;
wire        wb_m2s_or1k_d_ps2_0_cyc;
wire        wb_m2s_or1k_d_ps2_0_stb;
wire  [2:0] wb_m2s_or1k_d_ps2_0_cti;
wire  [1:0] wb_m2s_or1k_d_ps2_0_bte;
wire [31:0] wb_s2m_or1k_d_ps2_0_dat;
wire        wb_s2m_or1k_d_ps2_0_ack;
wire        wb_s2m_or1k_d_ps2_0_err;
wire        wb_s2m_or1k_d_ps2_0_rty;
wire [31:0] wb_m2s_or1k_d_i2c_temp_adr;
wire [31:0] wb_m2s_or1k_d_i2c_temp_dat;
wire  [3:0] wb_m2s_or1k_d_i2c_temp_sel;
wire        wb_m2s_or1k_d_i2c_temp_we;
wire        wb_m2s_or1k_d_i2c_temp_cyc;
wire        wb_m2s_or1k_d_i2c_temp_stb;
wire  [2:0] wb_m2s_or1k_d_i2c_temp_cti;
wire  [1:0] wb_m2s_or1k_d_i2c_temp_bte;
wire [31:0] wb_s2m_or1k_d_i2c_temp_dat;
wire        wb_s2m_or1k_d_i2c_temp_ack;
wire        wb_s2m_or1k_d_i2c_temp_err;
wire        wb_s2m_or1k_d_i2c_temp_rty;
wire [31:0] wb_m2s_or1k_d_spi_flash_adr;
wire [31:0] wb_m2s_or1k_d_spi_flash_dat;
wire  [3:0] wb_m2s_or1k_d_spi_flash_sel;
wire        wb_m2s_or1k_d_spi_flash_we;
wire        wb_m2s_or1k_d_spi_flash_cyc;
wire        wb_m2s_or1k_d_spi_flash_stb;
wire  [2:0] wb_m2s_or1k_d_spi_flash_cti;
wire  [1:0] wb_m2s_or1k_d_spi_flash_bte;
wire [31:0] wb_s2m_or1k_d_spi_flash_dat;
wire        wb_s2m_or1k_d_spi_flash_ack;
wire        wb_s2m_or1k_d_spi_flash_err;
wire        wb_s2m_or1k_d_spi_flash_rty;
wire [31:0] wb_m2s_or1k_d_spi_accel_adr;
wire [31:0] wb_m2s_or1k_d_spi_accel_dat;
wire  [3:0] wb_m2s_or1k_d_spi_accel_sel;
wire        wb_m2s_or1k_d_spi_accel_we;
wire        wb_m2s_or1k_d_spi_accel_cyc;
wire        wb_m2s_or1k_d_spi_accel_stb;
wire  [2:0] wb_m2s_or1k_d_spi_accel_cti;
wire  [1:0] wb_m2s_or1k_d_spi_accel_bte;
wire [31:0] wb_s2m_or1k_d_spi_accel_dat;
wire        wb_s2m_or1k_d_spi_accel_ack;
wire        wb_s2m_or1k_d_spi_accel_err;
wire        wb_s2m_or1k_d_spi_accel_rty;
wire [31:0] wb_m2s_or1k_d_xadc0_adr;
wire [31:0] wb_m2s_or1k_d_xadc0_dat;
wire  [3:0] wb_m2s_or1k_d_xadc0_sel;
wire        wb_m2s_or1k_d_xadc0_we;
wire        wb_m2s_or1k_d_xadc0_cyc;
wire        wb_m2s_or1k_d_xadc0_stb;
wire  [2:0] wb_m2s_or1k_d_xadc0_cti;
wire  [1:0] wb_m2s_or1k_d_xadc0_bte;
wire [31:0] wb_s2m_or1k_d_xadc0_dat;
wire        wb_s2m_or1k_d_xadc0_ack;
wire        wb_s2m_or1k_d_xadc0_err;
wire        wb_s2m_or1k_d_xadc0_rty;
wire [31:0] wb_m2s_or1k_d_ddr2_cfg0_adr;
wire [31:0] wb_m2s_or1k_d_ddr2_cfg0_dat;
wire  [3:0] wb_m2s_or1k_d_ddr2_cfg0_sel;
wire        wb_m2s_or1k_d_ddr2_cfg0_we;
wire        wb_m2s_or1k_d_ddr2_cfg0_cyc;
wire        wb_m2s_or1k_d_ddr2_cfg0_stb;
wire  [2:0] wb_m2s_or1k_d_ddr2_cfg0_cti;
wire  [1:0] wb_m2s_or1k_d_ddr2_cfg0_bte;
wire [31:0] wb_s2m_or1k_d_ddr2_cfg0_dat;
wire        wb_s2m_or1k_d_ddr2_cfg0_ack;
wire        wb_s2m_or1k_d_ddr2_cfg0_err;
wire        wb_s2m_or1k_d_ddr2_cfg0_rty;
wire [31:0] wb_m2s_dbg_ddr2_adr;
wire [31:0] wb_m2s_dbg_ddr2_dat;
wire  [3:0] wb_m2s_dbg_ddr2_sel;
wire        wb_m2s_dbg_ddr2_we;
wire        wb_m2s_dbg_ddr2_cyc;
wire        wb_m2s_dbg_ddr2_stb;
wire  [2:0] wb_m2s_dbg_ddr2_cti;
wire  [1:0] wb_m2s_dbg_ddr2_bte;
wire [31:0] wb_s2m_dbg_ddr2_dat;
wire        wb_s2m_dbg_ddr2_ack;
wire        wb_s2m_dbg_ddr2_err;
wire        wb_s2m_dbg_ddr2_rty;
wire [31:0] wb_m2s_dbg_rom0_adr;
wire [31:0] wb_m2s_dbg_rom0_dat;
wire  [3:0] wb_m2s_dbg_rom0_sel;
wire        wb_m2s_dbg_rom0_we;
wire        wb_m2s_dbg_rom0_cyc;
wire        wb_m2s_dbg_rom0_stb;
wire  [2:0] wb_m2s_dbg_rom0_cti;
wire  [1:0] wb_m2s_dbg_rom0_bte;
wire [31:0] wb_s2m_dbg_rom0_dat;
wire        wb_s2m_dbg_rom0_ack;
wire        wb_s2m_dbg_rom0_err;
wire        wb_s2m_dbg_rom0_rty;
wire [31:0] wb_m2s_dbg_uart0_adr;
wire [31:0] wb_m2s_dbg_uart0_dat;
wire  [3:0] wb_m2s_dbg_uart0_sel;
wire        wb_m2s_dbg_uart0_we;
wire        wb_m2s_dbg_uart0_cyc;
wire        wb_m2s_dbg_uart0_stb;
wire  [2:0] wb_m2s_dbg_uart0_cti;
wire  [1:0] wb_m2s_dbg_uart0_bte;
wire [31:0] wb_s2m_dbg_uart0_dat;
wire        wb_s2m_dbg_uart0_ack;
wire        wb_s2m_dbg_uart0_err;
wire        wb_s2m_dbg_uart0_rty;
wire [31:0] wb_m2s_dbg_gpio_sw_adr;
wire [31:0] wb_m2s_dbg_gpio_sw_dat;
wire  [3:0] wb_m2s_dbg_gpio_sw_sel;
wire        wb_m2s_dbg_gpio_sw_we;
wire        wb_m2s_dbg_gpio_sw_cyc;
wire        wb_m2s_dbg_gpio_sw_stb;
wire  [2:0] wb_m2s_dbg_gpio_sw_cti;
wire  [1:0] wb_m2s_dbg_gpio_sw_bte;
wire [31:0] wb_s2m_dbg_gpio_sw_dat;
wire        wb_s2m_dbg_gpio_sw_ack;
wire        wb_s2m_dbg_gpio_sw_err;
wire        wb_s2m_dbg_gpio_sw_rty;
wire [31:0] wb_m2s_dbg_gpio_pbtn_adr;
wire [31:0] wb_m2s_dbg_gpio_pbtn_dat;
wire  [3:0] wb_m2s_dbg_gpio_pbtn_sel;
wire        wb_m2s_dbg_gpio_pbtn_we;
wire        wb_m2s_dbg_gpio_pbtn_cyc;
wire        wb_m2s_dbg_gpio_pbtn_stb;
wire  [2:0] wb_m2s_dbg_gpio_pbtn_cti;
wire  [1:0] wb_m2s_dbg_gpio_pbtn_bte;
wire [31:0] wb_s2m_dbg_gpio_pbtn_dat;
wire        wb_s2m_dbg_gpio_pbtn_ack;
wire        wb_s2m_dbg_gpio_pbtn_err;
wire        wb_s2m_dbg_gpio_pbtn_rty;
wire [31:0] wb_m2s_dbg_gpio_led_adr;
wire [31:0] wb_m2s_dbg_gpio_led_dat;
wire  [3:0] wb_m2s_dbg_gpio_led_sel;
wire        wb_m2s_dbg_gpio_led_we;
wire        wb_m2s_dbg_gpio_led_cyc;
wire        wb_m2s_dbg_gpio_led_stb;
wire  [2:0] wb_m2s_dbg_gpio_led_cti;
wire  [1:0] wb_m2s_dbg_gpio_led_bte;
wire [31:0] wb_s2m_dbg_gpio_led_dat;
wire        wb_s2m_dbg_gpio_led_ack;
wire        wb_s2m_dbg_gpio_led_err;
wire        wb_s2m_dbg_gpio_led_rty;
wire [31:0] wb_m2s_dbg_gpio_pmod_adr;
wire [31:0] wb_m2s_dbg_gpio_pmod_dat;
wire  [3:0] wb_m2s_dbg_gpio_pmod_sel;
wire        wb_m2s_dbg_gpio_pmod_we;
wire        wb_m2s_dbg_gpio_pmod_cyc;
wire        wb_m2s_dbg_gpio_pmod_stb;
wire  [2:0] wb_m2s_dbg_gpio_pmod_cti;
wire  [1:0] wb_m2s_dbg_gpio_pmod_bte;
wire [31:0] wb_s2m_dbg_gpio_pmod_dat;
wire        wb_s2m_dbg_gpio_pmod_ack;
wire        wb_s2m_dbg_gpio_pmod_err;
wire        wb_s2m_dbg_gpio_pmod_rty;
wire [31:0] wb_m2s_dbg_sseg_ctrl_adr;
wire [31:0] wb_m2s_dbg_sseg_ctrl_dat;
wire  [3:0] wb_m2s_dbg_sseg_ctrl_sel;
wire        wb_m2s_dbg_sseg_ctrl_we;
wire        wb_m2s_dbg_sseg_ctrl_cyc;
wire        wb_m2s_dbg_sseg_ctrl_stb;
wire  [2:0] wb_m2s_dbg_sseg_ctrl_cti;
wire  [1:0] wb_m2s_dbg_sseg_ctrl_bte;
wire [31:0] wb_s2m_dbg_sseg_ctrl_dat;
wire        wb_s2m_dbg_sseg_ctrl_ack;
wire        wb_s2m_dbg_sseg_ctrl_err;
wire        wb_s2m_dbg_sseg_ctrl_rty;
wire [31:0] wb_m2s_dbg_rgb_led_adr;
wire [31:0] wb_m2s_dbg_rgb_led_dat;
wire  [3:0] wb_m2s_dbg_rgb_led_sel;
wire        wb_m2s_dbg_rgb_led_we;
wire        wb_m2s_dbg_rgb_led_cyc;
wire        wb_m2s_dbg_rgb_led_stb;
wire  [2:0] wb_m2s_dbg_rgb_led_cti;
wire  [1:0] wb_m2s_dbg_rgb_led_bte;
wire [31:0] wb_s2m_dbg_rgb_led_dat;
wire        wb_s2m_dbg_rgb_led_ack;
wire        wb_s2m_dbg_rgb_led_err;
wire        wb_s2m_dbg_rgb_led_rty;
wire [31:0] wb_m2s_dbg_ps2_0_adr;
wire [31:0] wb_m2s_dbg_ps2_0_dat;
wire  [3:0] wb_m2s_dbg_ps2_0_sel;
wire        wb_m2s_dbg_ps2_0_we;
wire        wb_m2s_dbg_ps2_0_cyc;
wire        wb_m2s_dbg_ps2_0_stb;
wire  [2:0] wb_m2s_dbg_ps2_0_cti;
wire  [1:0] wb_m2s_dbg_ps2_0_bte;
wire [31:0] wb_s2m_dbg_ps2_0_dat;
wire        wb_s2m_dbg_ps2_0_ack;
wire        wb_s2m_dbg_ps2_0_err;
wire        wb_s2m_dbg_ps2_0_rty;
wire [31:0] wb_m2s_dbg_i2c_temp_adr;
wire [31:0] wb_m2s_dbg_i2c_temp_dat;
wire  [3:0] wb_m2s_dbg_i2c_temp_sel;
wire        wb_m2s_dbg_i2c_temp_we;
wire        wb_m2s_dbg_i2c_temp_cyc;
wire        wb_m2s_dbg_i2c_temp_stb;
wire  [2:0] wb_m2s_dbg_i2c_temp_cti;
wire  [1:0] wb_m2s_dbg_i2c_temp_bte;
wire [31:0] wb_s2m_dbg_i2c_temp_dat;
wire        wb_s2m_dbg_i2c_temp_ack;
wire        wb_s2m_dbg_i2c_temp_err;
wire        wb_s2m_dbg_i2c_temp_rty;
wire [31:0] wb_m2s_dbg_spi_flash_adr;
wire [31:0] wb_m2s_dbg_spi_flash_dat;
wire  [3:0] wb_m2s_dbg_spi_flash_sel;
wire        wb_m2s_dbg_spi_flash_we;
wire        wb_m2s_dbg_spi_flash_cyc;
wire        wb_m2s_dbg_spi_flash_stb;
wire  [2:0] wb_m2s_dbg_spi_flash_cti;
wire  [1:0] wb_m2s_dbg_spi_flash_bte;
wire [31:0] wb_s2m_dbg_spi_flash_dat;
wire        wb_s2m_dbg_spi_flash_ack;
wire        wb_s2m_dbg_spi_flash_err;
wire        wb_s2m_dbg_spi_flash_rty;
wire [31:0] wb_m2s_dbg_spi_accel_adr;
wire [31:0] wb_m2s_dbg_spi_accel_dat;
wire  [3:0] wb_m2s_dbg_spi_accel_sel;
wire        wb_m2s_dbg_spi_accel_we;
wire        wb_m2s_dbg_spi_accel_cyc;
wire        wb_m2s_dbg_spi_accel_stb;
wire  [2:0] wb_m2s_dbg_spi_accel_cti;
wire  [1:0] wb_m2s_dbg_spi_accel_bte;
wire [31:0] wb_s2m_dbg_spi_accel_dat;
wire        wb_s2m_dbg_spi_accel_ack;
wire        wb_s2m_dbg_spi_accel_err;
wire        wb_s2m_dbg_spi_accel_rty;
wire [31:0] wb_m2s_dbg_xadc0_adr;
wire [31:0] wb_m2s_dbg_xadc0_dat;
wire  [3:0] wb_m2s_dbg_xadc0_sel;
wire        wb_m2s_dbg_xadc0_we;
wire        wb_m2s_dbg_xadc0_cyc;
wire        wb_m2s_dbg_xadc0_stb;
wire  [2:0] wb_m2s_dbg_xadc0_cti;
wire  [1:0] wb_m2s_dbg_xadc0_bte;
wire [31:0] wb_s2m_dbg_xadc0_dat;
wire        wb_s2m_dbg_xadc0_ack;
wire        wb_s2m_dbg_xadc0_err;
wire        wb_s2m_dbg_xadc0_rty;
wire [31:0] wb_m2s_dbg_ddr2_cfg0_adr;
wire [31:0] wb_m2s_dbg_ddr2_cfg0_dat;
wire  [3:0] wb_m2s_dbg_ddr2_cfg0_sel;
wire        wb_m2s_dbg_ddr2_cfg0_we;
wire        wb_m2s_dbg_ddr2_cfg0_cyc;
wire        wb_m2s_dbg_ddr2_cfg0_stb;
wire  [2:0] wb_m2s_dbg_ddr2_cfg0_cti;
wire  [1:0] wb_m2s_dbg_ddr2_cfg0_bte;
wire [31:0] wb_s2m_dbg_ddr2_cfg0_dat;
wire        wb_s2m_dbg_ddr2_cfg0_ack;
wire        wb_s2m_dbg_ddr2_cfg0_err;
wire        wb_s2m_dbg_ddr2_cfg0_rty;
wire [31:0] wb_m2s_dbg_rs232_ddr2_adr;
wire [31:0] wb_m2s_dbg_rs232_ddr2_dat;
wire  [3:0] wb_m2s_dbg_rs232_ddr2_sel;
wire        wb_m2s_dbg_rs232_ddr2_we;
wire        wb_m2s_dbg_rs232_ddr2_cyc;
wire        wb_m2s_dbg_rs232_ddr2_stb;
wire  [2:0] wb_m2s_dbg_rs232_ddr2_cti;
wire  [1:0] wb_m2s_dbg_rs232_ddr2_bte;
wire [31:0] wb_s2m_dbg_rs232_ddr2_dat;
wire        wb_s2m_dbg_rs232_ddr2_ack;
wire        wb_s2m_dbg_rs232_ddr2_err;
wire        wb_s2m_dbg_rs232_ddr2_rty;
wire [31:0] wb_m2s_dbg_rs232_rom0_adr;
wire [31:0] wb_m2s_dbg_rs232_rom0_dat;
wire  [3:0] wb_m2s_dbg_rs232_rom0_sel;
wire        wb_m2s_dbg_rs232_rom0_we;
wire        wb_m2s_dbg_rs232_rom0_cyc;
wire        wb_m2s_dbg_rs232_rom0_stb;
wire  [2:0] wb_m2s_dbg_rs232_rom0_cti;
wire  [1:0] wb_m2s_dbg_rs232_rom0_bte;
wire [31:0] wb_s2m_dbg_rs232_rom0_dat;
wire        wb_s2m_dbg_rs232_rom0_ack;
wire        wb_s2m_dbg_rs232_rom0_err;
wire        wb_s2m_dbg_rs232_rom0_rty;
wire [31:0] wb_m2s_dbg_rs232_uart0_adr;
wire [31:0] wb_m2s_dbg_rs232_uart0_dat;
wire  [3:0] wb_m2s_dbg_rs232_uart0_sel;
wire        wb_m2s_dbg_rs232_uart0_we;
wire        wb_m2s_dbg_rs232_uart0_cyc;
wire        wb_m2s_dbg_rs232_uart0_stb;
wire  [2:0] wb_m2s_dbg_rs232_uart0_cti;
wire  [1:0] wb_m2s_dbg_rs232_uart0_bte;
wire [31:0] wb_s2m_dbg_rs232_uart0_dat;
wire        wb_s2m_dbg_rs232_uart0_ack;
wire        wb_s2m_dbg_rs232_uart0_err;
wire        wb_s2m_dbg_rs232_uart0_rty;
wire [31:0] wb_m2s_dbg_rs232_gpio_sw_adr;
wire [31:0] wb_m2s_dbg_rs232_gpio_sw_dat;
wire  [3:0] wb_m2s_dbg_rs232_gpio_sw_sel;
wire        wb_m2s_dbg_rs232_gpio_sw_we;
wire        wb_m2s_dbg_rs232_gpio_sw_cyc;
wire        wb_m2s_dbg_rs232_gpio_sw_stb;
wire  [2:0] wb_m2s_dbg_rs232_gpio_sw_cti;
wire  [1:0] wb_m2s_dbg_rs232_gpio_sw_bte;
wire [31:0] wb_s2m_dbg_rs232_gpio_sw_dat;
wire        wb_s2m_dbg_rs232_gpio_sw_ack;
wire        wb_s2m_dbg_rs232_gpio_sw_err;
wire        wb_s2m_dbg_rs232_gpio_sw_rty;
wire [31:0] wb_m2s_dbg_rs232_gpio_pbtn_adr;
wire [31:0] wb_m2s_dbg_rs232_gpio_pbtn_dat;
wire  [3:0] wb_m2s_dbg_rs232_gpio_pbtn_sel;
wire        wb_m2s_dbg_rs232_gpio_pbtn_we;
wire        wb_m2s_dbg_rs232_gpio_pbtn_cyc;
wire        wb_m2s_dbg_rs232_gpio_pbtn_stb;
wire  [2:0] wb_m2s_dbg_rs232_gpio_pbtn_cti;
wire  [1:0] wb_m2s_dbg_rs232_gpio_pbtn_bte;
wire [31:0] wb_s2m_dbg_rs232_gpio_pbtn_dat;
wire        wb_s2m_dbg_rs232_gpio_pbtn_ack;
wire        wb_s2m_dbg_rs232_gpio_pbtn_err;
wire        wb_s2m_dbg_rs232_gpio_pbtn_rty;
wire [31:0] wb_m2s_dbg_rs232_gpio_led_adr;
wire [31:0] wb_m2s_dbg_rs232_gpio_led_dat;
wire  [3:0] wb_m2s_dbg_rs232_gpio_led_sel;
wire        wb_m2s_dbg_rs232_gpio_led_we;
wire        wb_m2s_dbg_rs232_gpio_led_cyc;
wire        wb_m2s_dbg_rs232_gpio_led_stb;
wire  [2:0] wb_m2s_dbg_rs232_gpio_led_cti;
wire  [1:0] wb_m2s_dbg_rs232_gpio_led_bte;
wire [31:0] wb_s2m_dbg_rs232_gpio_led_dat;
wire        wb_s2m_dbg_rs232_gpio_led_ack;
wire        wb_s2m_dbg_rs232_gpio_led_err;
wire        wb_s2m_dbg_rs232_gpio_led_rty;
wire [31:0] wb_m2s_dbg_rs232_gpio_pmod_adr;
wire [31:0] wb_m2s_dbg_rs232_gpio_pmod_dat;
wire  [3:0] wb_m2s_dbg_rs232_gpio_pmod_sel;
wire        wb_m2s_dbg_rs232_gpio_pmod_we;
wire        wb_m2s_dbg_rs232_gpio_pmod_cyc;
wire        wb_m2s_dbg_rs232_gpio_pmod_stb;
wire  [2:0] wb_m2s_dbg_rs232_gpio_pmod_cti;
wire  [1:0] wb_m2s_dbg_rs232_gpio_pmod_bte;
wire [31:0] wb_s2m_dbg_rs232_gpio_pmod_dat;
wire        wb_s2m_dbg_rs232_gpio_pmod_ack;
wire        wb_s2m_dbg_rs232_gpio_pmod_err;
wire        wb_s2m_dbg_rs232_gpio_pmod_rty;
wire [31:0] wb_m2s_dbg_rs232_sseg_ctrl_adr;
wire [31:0] wb_m2s_dbg_rs232_sseg_ctrl_dat;
wire  [3:0] wb_m2s_dbg_rs232_sseg_ctrl_sel;
wire        wb_m2s_dbg_rs232_sseg_ctrl_we;
wire        wb_m2s_dbg_rs232_sseg_ctrl_cyc;
wire        wb_m2s_dbg_rs232_sseg_ctrl_stb;
wire  [2:0] wb_m2s_dbg_rs232_sseg_ctrl_cti;
wire  [1:0] wb_m2s_dbg_rs232_sseg_ctrl_bte;
wire [31:0] wb_s2m_dbg_rs232_sseg_ctrl_dat;
wire        wb_s2m_dbg_rs232_sseg_ctrl_ack;
wire        wb_s2m_dbg_rs232_sseg_ctrl_err;
wire        wb_s2m_dbg_rs232_sseg_ctrl_rty;
wire [31:0] wb_m2s_dbg_rs232_rgb_led_adr;
wire [31:0] wb_m2s_dbg_rs232_rgb_led_dat;
wire  [3:0] wb_m2s_dbg_rs232_rgb_led_sel;
wire        wb_m2s_dbg_rs232_rgb_led_we;
wire        wb_m2s_dbg_rs232_rgb_led_cyc;
wire        wb_m2s_dbg_rs232_rgb_led_stb;
wire  [2:0] wb_m2s_dbg_rs232_rgb_led_cti;
wire  [1:0] wb_m2s_dbg_rs232_rgb_led_bte;
wire [31:0] wb_s2m_dbg_rs232_rgb_led_dat;
wire        wb_s2m_dbg_rs232_rgb_led_ack;
wire        wb_s2m_dbg_rs232_rgb_led_err;
wire        wb_s2m_dbg_rs232_rgb_led_rty;
wire [31:0] wb_m2s_dbg_rs232_ps2_0_adr;
wire [31:0] wb_m2s_dbg_rs232_ps2_0_dat;
wire  [3:0] wb_m2s_dbg_rs232_ps2_0_sel;
wire        wb_m2s_dbg_rs232_ps2_0_we;
wire        wb_m2s_dbg_rs232_ps2_0_cyc;
wire        wb_m2s_dbg_rs232_ps2_0_stb;
wire  [2:0] wb_m2s_dbg_rs232_ps2_0_cti;
wire  [1:0] wb_m2s_dbg_rs232_ps2_0_bte;
wire [31:0] wb_s2m_dbg_rs232_ps2_0_dat;
wire        wb_s2m_dbg_rs232_ps2_0_ack;
wire        wb_s2m_dbg_rs232_ps2_0_err;
wire        wb_s2m_dbg_rs232_ps2_0_rty;
wire [31:0] wb_m2s_dbg_rs232_i2c_temp_adr;
wire [31:0] wb_m2s_dbg_rs232_i2c_temp_dat;
wire  [3:0] wb_m2s_dbg_rs232_i2c_temp_sel;
wire        wb_m2s_dbg_rs232_i2c_temp_we;
wire        wb_m2s_dbg_rs232_i2c_temp_cyc;
wire        wb_m2s_dbg_rs232_i2c_temp_stb;
wire  [2:0] wb_m2s_dbg_rs232_i2c_temp_cti;
wire  [1:0] wb_m2s_dbg_rs232_i2c_temp_bte;
wire [31:0] wb_s2m_dbg_rs232_i2c_temp_dat;
wire        wb_s2m_dbg_rs232_i2c_temp_ack;
wire        wb_s2m_dbg_rs232_i2c_temp_err;
wire        wb_s2m_dbg_rs232_i2c_temp_rty;
wire [31:0] wb_m2s_dbg_rs232_spi_flash_adr;
wire [31:0] wb_m2s_dbg_rs232_spi_flash_dat;
wire  [3:0] wb_m2s_dbg_rs232_spi_flash_sel;
wire        wb_m2s_dbg_rs232_spi_flash_we;
wire        wb_m2s_dbg_rs232_spi_flash_cyc;
wire        wb_m2s_dbg_rs232_spi_flash_stb;
wire  [2:0] wb_m2s_dbg_rs232_spi_flash_cti;
wire  [1:0] wb_m2s_dbg_rs232_spi_flash_bte;
wire [31:0] wb_s2m_dbg_rs232_spi_flash_dat;
wire        wb_s2m_dbg_rs232_spi_flash_ack;
wire        wb_s2m_dbg_rs232_spi_flash_err;
wire        wb_s2m_dbg_rs232_spi_flash_rty;
wire [31:0] wb_m2s_dbg_rs232_spi_accel_adr;
wire [31:0] wb_m2s_dbg_rs232_spi_accel_dat;
wire  [3:0] wb_m2s_dbg_rs232_spi_accel_sel;
wire        wb_m2s_dbg_rs232_spi_accel_we;
wire        wb_m2s_dbg_rs232_spi_accel_cyc;
wire        wb_m2s_dbg_rs232_spi_accel_stb;
wire  [2:0] wb_m2s_dbg_rs232_spi_accel_cti;
wire  [1:0] wb_m2s_dbg_rs232_spi_accel_bte;
wire [31:0] wb_s2m_dbg_rs232_spi_accel_dat;
wire        wb_s2m_dbg_rs232_spi_accel_ack;
wire        wb_s2m_dbg_rs232_spi_accel_err;
wire        wb_s2m_dbg_rs232_spi_accel_rty;
wire [31:0] wb_m2s_dbg_rs232_xadc0_adr;
wire [31:0] wb_m2s_dbg_rs232_xadc0_dat;
wire  [3:0] wb_m2s_dbg_rs232_xadc0_sel;
wire        wb_m2s_dbg_rs232_xadc0_we;
wire        wb_m2s_dbg_rs232_xadc0_cyc;
wire        wb_m2s_dbg_rs232_xadc0_stb;
wire  [2:0] wb_m2s_dbg_rs232_xadc0_cti;
wire  [1:0] wb_m2s_dbg_rs232_xadc0_bte;
wire [31:0] wb_s2m_dbg_rs232_xadc0_dat;
wire        wb_s2m_dbg_rs232_xadc0_ack;
wire        wb_s2m_dbg_rs232_xadc0_err;
wire        wb_s2m_dbg_rs232_xadc0_rty;
wire [31:0] wb_m2s_dbg_rs232_ddr2_cfg0_adr;
wire [31:0] wb_m2s_dbg_rs232_ddr2_cfg0_dat;
wire  [3:0] wb_m2s_dbg_rs232_ddr2_cfg0_sel;
wire        wb_m2s_dbg_rs232_ddr2_cfg0_we;
wire        wb_m2s_dbg_rs232_ddr2_cfg0_cyc;
wire        wb_m2s_dbg_rs232_ddr2_cfg0_stb;
wire  [2:0] wb_m2s_dbg_rs232_ddr2_cfg0_cti;
wire  [1:0] wb_m2s_dbg_rs232_ddr2_cfg0_bte;
wire [31:0] wb_s2m_dbg_rs232_ddr2_cfg0_dat;
wire        wb_s2m_dbg_rs232_ddr2_cfg0_ack;
wire        wb_s2m_dbg_rs232_ddr2_cfg0_err;
wire        wb_s2m_dbg_rs232_ddr2_cfg0_rty;
wire [31:0] wb_m2s_resize_uart0_adr;
wire [31:0] wb_m2s_resize_uart0_dat;
wire  [3:0] wb_m2s_resize_uart0_sel;
wire        wb_m2s_resize_uart0_we;
wire        wb_m2s_resize_uart0_cyc;
wire        wb_m2s_resize_uart0_stb;
wire  [2:0] wb_m2s_resize_uart0_cti;
wire  [1:0] wb_m2s_resize_uart0_bte;
wire [31:0] wb_s2m_resize_uart0_dat;
wire        wb_s2m_resize_uart0_ack;
wire        wb_s2m_resize_uart0_err;
wire        wb_s2m_resize_uart0_rty;
wire [31:0] wb_m2s_resize_gpio_sw_adr;
wire [31:0] wb_m2s_resize_gpio_sw_dat;
wire  [3:0] wb_m2s_resize_gpio_sw_sel;
wire        wb_m2s_resize_gpio_sw_we;
wire        wb_m2s_resize_gpio_sw_cyc;
wire        wb_m2s_resize_gpio_sw_stb;
wire  [2:0] wb_m2s_resize_gpio_sw_cti;
wire  [1:0] wb_m2s_resize_gpio_sw_bte;
wire [31:0] wb_s2m_resize_gpio_sw_dat;
wire        wb_s2m_resize_gpio_sw_ack;
wire        wb_s2m_resize_gpio_sw_err;
wire        wb_s2m_resize_gpio_sw_rty;
wire [31:0] wb_m2s_resize_gpio_pbtn_adr;
wire [31:0] wb_m2s_resize_gpio_pbtn_dat;
wire  [3:0] wb_m2s_resize_gpio_pbtn_sel;
wire        wb_m2s_resize_gpio_pbtn_we;
wire        wb_m2s_resize_gpio_pbtn_cyc;
wire        wb_m2s_resize_gpio_pbtn_stb;
wire  [2:0] wb_m2s_resize_gpio_pbtn_cti;
wire  [1:0] wb_m2s_resize_gpio_pbtn_bte;
wire [31:0] wb_s2m_resize_gpio_pbtn_dat;
wire        wb_s2m_resize_gpio_pbtn_ack;
wire        wb_s2m_resize_gpio_pbtn_err;
wire        wb_s2m_resize_gpio_pbtn_rty;
wire [31:0] wb_m2s_resize_gpio_led_adr;
wire [31:0] wb_m2s_resize_gpio_led_dat;
wire  [3:0] wb_m2s_resize_gpio_led_sel;
wire        wb_m2s_resize_gpio_led_we;
wire        wb_m2s_resize_gpio_led_cyc;
wire        wb_m2s_resize_gpio_led_stb;
wire  [2:0] wb_m2s_resize_gpio_led_cti;
wire  [1:0] wb_m2s_resize_gpio_led_bte;
wire [31:0] wb_s2m_resize_gpio_led_dat;
wire        wb_s2m_resize_gpio_led_ack;
wire        wb_s2m_resize_gpio_led_err;
wire        wb_s2m_resize_gpio_led_rty;
wire [31:0] wb_m2s_resize_sseg_ctrl_adr;
wire [31:0] wb_m2s_resize_sseg_ctrl_dat;
wire  [3:0] wb_m2s_resize_sseg_ctrl_sel;
wire        wb_m2s_resize_sseg_ctrl_we;
wire        wb_m2s_resize_sseg_ctrl_cyc;
wire        wb_m2s_resize_sseg_ctrl_stb;
wire  [2:0] wb_m2s_resize_sseg_ctrl_cti;
wire  [1:0] wb_m2s_resize_sseg_ctrl_bte;
wire [31:0] wb_s2m_resize_sseg_ctrl_dat;
wire        wb_s2m_resize_sseg_ctrl_ack;
wire        wb_s2m_resize_sseg_ctrl_err;
wire        wb_s2m_resize_sseg_ctrl_rty;
wire [31:0] wb_m2s_resize_rgb_led_adr;
wire [31:0] wb_m2s_resize_rgb_led_dat;
wire  [3:0] wb_m2s_resize_rgb_led_sel;
wire        wb_m2s_resize_rgb_led_we;
wire        wb_m2s_resize_rgb_led_cyc;
wire        wb_m2s_resize_rgb_led_stb;
wire  [2:0] wb_m2s_resize_rgb_led_cti;
wire  [1:0] wb_m2s_resize_rgb_led_bte;
wire [31:0] wb_s2m_resize_rgb_led_dat;
wire        wb_s2m_resize_rgb_led_ack;
wire        wb_s2m_resize_rgb_led_err;
wire        wb_s2m_resize_rgb_led_rty;
wire [31:0] wb_m2s_resize_ps2_0_adr;
wire [31:0] wb_m2s_resize_ps2_0_dat;
wire  [3:0] wb_m2s_resize_ps2_0_sel;
wire        wb_m2s_resize_ps2_0_we;
wire        wb_m2s_resize_ps2_0_cyc;
wire        wb_m2s_resize_ps2_0_stb;
wire  [2:0] wb_m2s_resize_ps2_0_cti;
wire  [1:0] wb_m2s_resize_ps2_0_bte;
wire [31:0] wb_s2m_resize_ps2_0_dat;
wire        wb_s2m_resize_ps2_0_ack;
wire        wb_s2m_resize_ps2_0_err;
wire        wb_s2m_resize_ps2_0_rty;
wire [31:0] wb_m2s_resize_xadc0_adr;
wire [31:0] wb_m2s_resize_xadc0_dat;
wire  [3:0] wb_m2s_resize_xadc0_sel;
wire        wb_m2s_resize_xadc0_we;
wire        wb_m2s_resize_xadc0_cyc;
wire        wb_m2s_resize_xadc0_stb;
wire  [2:0] wb_m2s_resize_xadc0_cti;
wire  [1:0] wb_m2s_resize_xadc0_bte;
wire [31:0] wb_s2m_resize_xadc0_dat;
wire        wb_s2m_resize_xadc0_ack;
wire        wb_s2m_resize_xadc0_err;
wire        wb_s2m_resize_xadc0_rty;
wire [31:0] wb_m2s_resize_ddr2_cfg0_adr;
wire [31:0] wb_m2s_resize_ddr2_cfg0_dat;
wire  [3:0] wb_m2s_resize_ddr2_cfg0_sel;
wire        wb_m2s_resize_ddr2_cfg0_we;
wire        wb_m2s_resize_ddr2_cfg0_cyc;
wire        wb_m2s_resize_ddr2_cfg0_stb;
wire  [2:0] wb_m2s_resize_ddr2_cfg0_cti;
wire  [1:0] wb_m2s_resize_ddr2_cfg0_bte;
wire [31:0] wb_s2m_resize_ddr2_cfg0_dat;
wire        wb_s2m_resize_ddr2_cfg0_ack;
wire        wb_s2m_resize_ddr2_cfg0_err;
wire        wb_s2m_resize_ddr2_cfg0_rty;
wire [31:0] wb_m2s_resize_spi_flash_adr;
wire [31:0] wb_m2s_resize_spi_flash_dat;
wire  [3:0] wb_m2s_resize_spi_flash_sel;
wire        wb_m2s_resize_spi_flash_we;
wire        wb_m2s_resize_spi_flash_cyc;
wire        wb_m2s_resize_spi_flash_stb;
wire  [2:0] wb_m2s_resize_spi_flash_cti;
wire  [1:0] wb_m2s_resize_spi_flash_bte;
wire [31:0] wb_s2m_resize_spi_flash_dat;
wire        wb_s2m_resize_spi_flash_ack;
wire        wb_s2m_resize_spi_flash_err;
wire        wb_s2m_resize_spi_flash_rty;
wire [31:0] wb_m2s_resize_spi_accel_adr;
wire [31:0] wb_m2s_resize_spi_accel_dat;
wire  [3:0] wb_m2s_resize_spi_accel_sel;
wire        wb_m2s_resize_spi_accel_we;
wire        wb_m2s_resize_spi_accel_cyc;
wire        wb_m2s_resize_spi_accel_stb;
wire  [2:0] wb_m2s_resize_spi_accel_cti;
wire  [1:0] wb_m2s_resize_spi_accel_bte;
wire [31:0] wb_s2m_resize_spi_accel_dat;
wire        wb_s2m_resize_spi_accel_ack;
wire        wb_s2m_resize_spi_accel_err;
wire        wb_s2m_resize_spi_accel_rty;
wire [31:0] wb_m2s_resize_i2c_temp_adr;
wire [31:0] wb_m2s_resize_i2c_temp_dat;
wire  [3:0] wb_m2s_resize_i2c_temp_sel;
wire        wb_m2s_resize_i2c_temp_we;
wire        wb_m2s_resize_i2c_temp_cyc;
wire        wb_m2s_resize_i2c_temp_stb;
wire  [2:0] wb_m2s_resize_i2c_temp_cti;
wire  [1:0] wb_m2s_resize_i2c_temp_bte;
wire [31:0] wb_s2m_resize_i2c_temp_dat;
wire        wb_s2m_resize_i2c_temp_ack;
wire        wb_s2m_resize_i2c_temp_err;
wire        wb_s2m_resize_i2c_temp_rty;

wb_mux
  #(.num_slaves (2),
    .MATCH_ADDR ({32'h00000000, 32'hf0000000}),
    .MATCH_MASK ({32'hf8000000, 32'hfffffc00}))
 wb_mux_or1k_i
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_or1k_i_adr_i),
    .wbm_dat_i (wb_or1k_i_dat_i),
    .wbm_sel_i (wb_or1k_i_sel_i),
    .wbm_we_i  (wb_or1k_i_we_i),
    .wbm_cyc_i (wb_or1k_i_cyc_i),
    .wbm_stb_i (wb_or1k_i_stb_i),
    .wbm_cti_i (wb_or1k_i_cti_i),
    .wbm_bte_i (wb_or1k_i_bte_i),
    .wbm_dat_o (wb_or1k_i_dat_o),
    .wbm_ack_o (wb_or1k_i_ack_o),
    .wbm_err_o (wb_or1k_i_err_o),
    .wbm_rty_o (wb_or1k_i_rty_o),
    .wbs_adr_o ({wb_m2s_or1k_i_ddr2_adr, wb_m2s_or1k_i_rom0_adr}),
    .wbs_dat_o ({wb_m2s_or1k_i_ddr2_dat, wb_m2s_or1k_i_rom0_dat}),
    .wbs_sel_o ({wb_m2s_or1k_i_ddr2_sel, wb_m2s_or1k_i_rom0_sel}),
    .wbs_we_o  ({wb_m2s_or1k_i_ddr2_we, wb_m2s_or1k_i_rom0_we}),
    .wbs_cyc_o ({wb_m2s_or1k_i_ddr2_cyc, wb_m2s_or1k_i_rom0_cyc}),
    .wbs_stb_o ({wb_m2s_or1k_i_ddr2_stb, wb_m2s_or1k_i_rom0_stb}),
    .wbs_cti_o ({wb_m2s_or1k_i_ddr2_cti, wb_m2s_or1k_i_rom0_cti}),
    .wbs_bte_o ({wb_m2s_or1k_i_ddr2_bte, wb_m2s_or1k_i_rom0_bte}),
    .wbs_dat_i ({wb_s2m_or1k_i_ddr2_dat, wb_s2m_or1k_i_rom0_dat}),
    .wbs_ack_i ({wb_s2m_or1k_i_ddr2_ack, wb_s2m_or1k_i_rom0_ack}),
    .wbs_err_i ({wb_s2m_or1k_i_ddr2_err, wb_s2m_or1k_i_rom0_err}),
    .wbs_rty_i ({wb_s2m_or1k_i_ddr2_rty, wb_s2m_or1k_i_rom0_rty}));

wb_mux
  #(.num_slaves (14),
    .MATCH_ADDR ({32'h00000000, 32'h90000000, 32'h91000000, 32'h91001000, 32'h91002000, 32'h91003000, 32'h92000000, 32'h93000000, 32'h94000000, 32'hd0000000, 32'hb0000000, 32'hb1000000, 32'h95000000, 32'h96000000}),
    .MATCH_MASK ({32'hf8000000, 32'hffffffe0, 32'hfffffff8, 32'hfffffff8, 32'hfffffff8, 32'hfffffff8, 32'hffffffc0, 32'hfffffff0, 32'hfffffff8, 32'hfffffff8, 32'hfffffff8, 32'hfffffff8, 32'hfffffc00, 32'hfffffff0}))
 wb_mux_or1k_d
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_or1k_d_adr_i),
    .wbm_dat_i (wb_or1k_d_dat_i),
    .wbm_sel_i (wb_or1k_d_sel_i),
    .wbm_we_i  (wb_or1k_d_we_i),
    .wbm_cyc_i (wb_or1k_d_cyc_i),
    .wbm_stb_i (wb_or1k_d_stb_i),
    .wbm_cti_i (wb_or1k_d_cti_i),
    .wbm_bte_i (wb_or1k_d_bte_i),
    .wbm_dat_o (wb_or1k_d_dat_o),
    .wbm_ack_o (wb_or1k_d_ack_o),
    .wbm_err_o (wb_or1k_d_err_o),
    .wbm_rty_o (wb_or1k_d_rty_o),
    .wbs_adr_o ({wb_m2s_or1k_d_ddr2_adr, wb_m2s_or1k_d_uart0_adr, wb_m2s_or1k_d_gpio_sw_adr, wb_m2s_or1k_d_gpio_pbtn_adr, wb_m2s_or1k_d_gpio_led_adr, wb_m2s_or1k_d_gpio_pmod_adr, wb_m2s_or1k_d_sseg_ctrl_adr, wb_m2s_or1k_d_rgb_led_adr, wb_m2s_or1k_d_ps2_0_adr, wb_m2s_or1k_d_i2c_temp_adr, wb_m2s_or1k_d_spi_flash_adr, wb_m2s_or1k_d_spi_accel_adr, wb_m2s_or1k_d_xadc0_adr, wb_m2s_or1k_d_ddr2_cfg0_adr}),
    .wbs_dat_o ({wb_m2s_or1k_d_ddr2_dat, wb_m2s_or1k_d_uart0_dat, wb_m2s_or1k_d_gpio_sw_dat, wb_m2s_or1k_d_gpio_pbtn_dat, wb_m2s_or1k_d_gpio_led_dat, wb_m2s_or1k_d_gpio_pmod_dat, wb_m2s_or1k_d_sseg_ctrl_dat, wb_m2s_or1k_d_rgb_led_dat, wb_m2s_or1k_d_ps2_0_dat, wb_m2s_or1k_d_i2c_temp_dat, wb_m2s_or1k_d_spi_flash_dat, wb_m2s_or1k_d_spi_accel_dat, wb_m2s_or1k_d_xadc0_dat, wb_m2s_or1k_d_ddr2_cfg0_dat}),
    .wbs_sel_o ({wb_m2s_or1k_d_ddr2_sel, wb_m2s_or1k_d_uart0_sel, wb_m2s_or1k_d_gpio_sw_sel, wb_m2s_or1k_d_gpio_pbtn_sel, wb_m2s_or1k_d_gpio_led_sel, wb_m2s_or1k_d_gpio_pmod_sel, wb_m2s_or1k_d_sseg_ctrl_sel, wb_m2s_or1k_d_rgb_led_sel, wb_m2s_or1k_d_ps2_0_sel, wb_m2s_or1k_d_i2c_temp_sel, wb_m2s_or1k_d_spi_flash_sel, wb_m2s_or1k_d_spi_accel_sel, wb_m2s_or1k_d_xadc0_sel, wb_m2s_or1k_d_ddr2_cfg0_sel}),
    .wbs_we_o  ({wb_m2s_or1k_d_ddr2_we, wb_m2s_or1k_d_uart0_we, wb_m2s_or1k_d_gpio_sw_we, wb_m2s_or1k_d_gpio_pbtn_we, wb_m2s_or1k_d_gpio_led_we, wb_m2s_or1k_d_gpio_pmod_we, wb_m2s_or1k_d_sseg_ctrl_we, wb_m2s_or1k_d_rgb_led_we, wb_m2s_or1k_d_ps2_0_we, wb_m2s_or1k_d_i2c_temp_we, wb_m2s_or1k_d_spi_flash_we, wb_m2s_or1k_d_spi_accel_we, wb_m2s_or1k_d_xadc0_we, wb_m2s_or1k_d_ddr2_cfg0_we}),
    .wbs_cyc_o ({wb_m2s_or1k_d_ddr2_cyc, wb_m2s_or1k_d_uart0_cyc, wb_m2s_or1k_d_gpio_sw_cyc, wb_m2s_or1k_d_gpio_pbtn_cyc, wb_m2s_or1k_d_gpio_led_cyc, wb_m2s_or1k_d_gpio_pmod_cyc, wb_m2s_or1k_d_sseg_ctrl_cyc, wb_m2s_or1k_d_rgb_led_cyc, wb_m2s_or1k_d_ps2_0_cyc, wb_m2s_or1k_d_i2c_temp_cyc, wb_m2s_or1k_d_spi_flash_cyc, wb_m2s_or1k_d_spi_accel_cyc, wb_m2s_or1k_d_xadc0_cyc, wb_m2s_or1k_d_ddr2_cfg0_cyc}),
    .wbs_stb_o ({wb_m2s_or1k_d_ddr2_stb, wb_m2s_or1k_d_uart0_stb, wb_m2s_or1k_d_gpio_sw_stb, wb_m2s_or1k_d_gpio_pbtn_stb, wb_m2s_or1k_d_gpio_led_stb, wb_m2s_or1k_d_gpio_pmod_stb, wb_m2s_or1k_d_sseg_ctrl_stb, wb_m2s_or1k_d_rgb_led_stb, wb_m2s_or1k_d_ps2_0_stb, wb_m2s_or1k_d_i2c_temp_stb, wb_m2s_or1k_d_spi_flash_stb, wb_m2s_or1k_d_spi_accel_stb, wb_m2s_or1k_d_xadc0_stb, wb_m2s_or1k_d_ddr2_cfg0_stb}),
    .wbs_cti_o ({wb_m2s_or1k_d_ddr2_cti, wb_m2s_or1k_d_uart0_cti, wb_m2s_or1k_d_gpio_sw_cti, wb_m2s_or1k_d_gpio_pbtn_cti, wb_m2s_or1k_d_gpio_led_cti, wb_m2s_or1k_d_gpio_pmod_cti, wb_m2s_or1k_d_sseg_ctrl_cti, wb_m2s_or1k_d_rgb_led_cti, wb_m2s_or1k_d_ps2_0_cti, wb_m2s_or1k_d_i2c_temp_cti, wb_m2s_or1k_d_spi_flash_cti, wb_m2s_or1k_d_spi_accel_cti, wb_m2s_or1k_d_xadc0_cti, wb_m2s_or1k_d_ddr2_cfg0_cti}),
    .wbs_bte_o ({wb_m2s_or1k_d_ddr2_bte, wb_m2s_or1k_d_uart0_bte, wb_m2s_or1k_d_gpio_sw_bte, wb_m2s_or1k_d_gpio_pbtn_bte, wb_m2s_or1k_d_gpio_led_bte, wb_m2s_or1k_d_gpio_pmod_bte, wb_m2s_or1k_d_sseg_ctrl_bte, wb_m2s_or1k_d_rgb_led_bte, wb_m2s_or1k_d_ps2_0_bte, wb_m2s_or1k_d_i2c_temp_bte, wb_m2s_or1k_d_spi_flash_bte, wb_m2s_or1k_d_spi_accel_bte, wb_m2s_or1k_d_xadc0_bte, wb_m2s_or1k_d_ddr2_cfg0_bte}),
    .wbs_dat_i ({wb_s2m_or1k_d_ddr2_dat, wb_s2m_or1k_d_uart0_dat, wb_s2m_or1k_d_gpio_sw_dat, wb_s2m_or1k_d_gpio_pbtn_dat, wb_s2m_or1k_d_gpio_led_dat, wb_s2m_or1k_d_gpio_pmod_dat, wb_s2m_or1k_d_sseg_ctrl_dat, wb_s2m_or1k_d_rgb_led_dat, wb_s2m_or1k_d_ps2_0_dat, wb_s2m_or1k_d_i2c_temp_dat, wb_s2m_or1k_d_spi_flash_dat, wb_s2m_or1k_d_spi_accel_dat, wb_s2m_or1k_d_xadc0_dat, wb_s2m_or1k_d_ddr2_cfg0_dat}),
    .wbs_ack_i ({wb_s2m_or1k_d_ddr2_ack, wb_s2m_or1k_d_uart0_ack, wb_s2m_or1k_d_gpio_sw_ack, wb_s2m_or1k_d_gpio_pbtn_ack, wb_s2m_or1k_d_gpio_led_ack, wb_s2m_or1k_d_gpio_pmod_ack, wb_s2m_or1k_d_sseg_ctrl_ack, wb_s2m_or1k_d_rgb_led_ack, wb_s2m_or1k_d_ps2_0_ack, wb_s2m_or1k_d_i2c_temp_ack, wb_s2m_or1k_d_spi_flash_ack, wb_s2m_or1k_d_spi_accel_ack, wb_s2m_or1k_d_xadc0_ack, wb_s2m_or1k_d_ddr2_cfg0_ack}),
    .wbs_err_i ({wb_s2m_or1k_d_ddr2_err, wb_s2m_or1k_d_uart0_err, wb_s2m_or1k_d_gpio_sw_err, wb_s2m_or1k_d_gpio_pbtn_err, wb_s2m_or1k_d_gpio_led_err, wb_s2m_or1k_d_gpio_pmod_err, wb_s2m_or1k_d_sseg_ctrl_err, wb_s2m_or1k_d_rgb_led_err, wb_s2m_or1k_d_ps2_0_err, wb_s2m_or1k_d_i2c_temp_err, wb_s2m_or1k_d_spi_flash_err, wb_s2m_or1k_d_spi_accel_err, wb_s2m_or1k_d_xadc0_err, wb_s2m_or1k_d_ddr2_cfg0_err}),
    .wbs_rty_i ({wb_s2m_or1k_d_ddr2_rty, wb_s2m_or1k_d_uart0_rty, wb_s2m_or1k_d_gpio_sw_rty, wb_s2m_or1k_d_gpio_pbtn_rty, wb_s2m_or1k_d_gpio_led_rty, wb_s2m_or1k_d_gpio_pmod_rty, wb_s2m_or1k_d_sseg_ctrl_rty, wb_s2m_or1k_d_rgb_led_rty, wb_s2m_or1k_d_ps2_0_rty, wb_s2m_or1k_d_i2c_temp_rty, wb_s2m_or1k_d_spi_flash_rty, wb_s2m_or1k_d_spi_accel_rty, wb_s2m_or1k_d_xadc0_rty, wb_s2m_or1k_d_ddr2_cfg0_rty}));

wb_mux
  #(.num_slaves (15),
    .MATCH_ADDR ({32'h00000000, 32'hf0000000, 32'h90000000, 32'h91000000, 32'h91001000, 32'h91002000, 32'h91003000, 32'h92000000, 32'h93000000, 32'h94000000, 32'hd0000000, 32'hb0000000, 32'hb1000000, 32'h95000000, 32'h96000000}),
    .MATCH_MASK ({32'hf8000000, 32'hfffffc00, 32'hffffffe0, 32'hfffffff8, 32'hfffffff8, 32'hfffffff8, 32'hfffffff8, 32'hffffffc0, 32'hfffffff0, 32'hfffffff8, 32'hfffffff8, 32'hfffffff8, 32'hfffffff8, 32'hfffffc00, 32'hfffffff0}))
 wb_mux_dbg
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_dbg_adr_i),
    .wbm_dat_i (wb_dbg_dat_i),
    .wbm_sel_i (wb_dbg_sel_i),
    .wbm_we_i  (wb_dbg_we_i),
    .wbm_cyc_i (wb_dbg_cyc_i),
    .wbm_stb_i (wb_dbg_stb_i),
    .wbm_cti_i (wb_dbg_cti_i),
    .wbm_bte_i (wb_dbg_bte_i),
    .wbm_dat_o (wb_dbg_dat_o),
    .wbm_ack_o (wb_dbg_ack_o),
    .wbm_err_o (wb_dbg_err_o),
    .wbm_rty_o (wb_dbg_rty_o),
    .wbs_adr_o ({wb_m2s_dbg_ddr2_adr, wb_m2s_dbg_rom0_adr, wb_m2s_dbg_uart0_adr, wb_m2s_dbg_gpio_sw_adr, wb_m2s_dbg_gpio_pbtn_adr, wb_m2s_dbg_gpio_led_adr, wb_m2s_dbg_gpio_pmod_adr, wb_m2s_dbg_sseg_ctrl_adr, wb_m2s_dbg_rgb_led_adr, wb_m2s_dbg_ps2_0_adr, wb_m2s_dbg_i2c_temp_adr, wb_m2s_dbg_spi_flash_adr, wb_m2s_dbg_spi_accel_adr, wb_m2s_dbg_xadc0_adr, wb_m2s_dbg_ddr2_cfg0_adr}),
    .wbs_dat_o ({wb_m2s_dbg_ddr2_dat, wb_m2s_dbg_rom0_dat, wb_m2s_dbg_uart0_dat, wb_m2s_dbg_gpio_sw_dat, wb_m2s_dbg_gpio_pbtn_dat, wb_m2s_dbg_gpio_led_dat, wb_m2s_dbg_gpio_pmod_dat, wb_m2s_dbg_sseg_ctrl_dat, wb_m2s_dbg_rgb_led_dat, wb_m2s_dbg_ps2_0_dat, wb_m2s_dbg_i2c_temp_dat, wb_m2s_dbg_spi_flash_dat, wb_m2s_dbg_spi_accel_dat, wb_m2s_dbg_xadc0_dat, wb_m2s_dbg_ddr2_cfg0_dat}),
    .wbs_sel_o ({wb_m2s_dbg_ddr2_sel, wb_m2s_dbg_rom0_sel, wb_m2s_dbg_uart0_sel, wb_m2s_dbg_gpio_sw_sel, wb_m2s_dbg_gpio_pbtn_sel, wb_m2s_dbg_gpio_led_sel, wb_m2s_dbg_gpio_pmod_sel, wb_m2s_dbg_sseg_ctrl_sel, wb_m2s_dbg_rgb_led_sel, wb_m2s_dbg_ps2_0_sel, wb_m2s_dbg_i2c_temp_sel, wb_m2s_dbg_spi_flash_sel, wb_m2s_dbg_spi_accel_sel, wb_m2s_dbg_xadc0_sel, wb_m2s_dbg_ddr2_cfg0_sel}),
    .wbs_we_o  ({wb_m2s_dbg_ddr2_we, wb_m2s_dbg_rom0_we, wb_m2s_dbg_uart0_we, wb_m2s_dbg_gpio_sw_we, wb_m2s_dbg_gpio_pbtn_we, wb_m2s_dbg_gpio_led_we, wb_m2s_dbg_gpio_pmod_we, wb_m2s_dbg_sseg_ctrl_we, wb_m2s_dbg_rgb_led_we, wb_m2s_dbg_ps2_0_we, wb_m2s_dbg_i2c_temp_we, wb_m2s_dbg_spi_flash_we, wb_m2s_dbg_spi_accel_we, wb_m2s_dbg_xadc0_we, wb_m2s_dbg_ddr2_cfg0_we}),
    .wbs_cyc_o ({wb_m2s_dbg_ddr2_cyc, wb_m2s_dbg_rom0_cyc, wb_m2s_dbg_uart0_cyc, wb_m2s_dbg_gpio_sw_cyc, wb_m2s_dbg_gpio_pbtn_cyc, wb_m2s_dbg_gpio_led_cyc, wb_m2s_dbg_gpio_pmod_cyc, wb_m2s_dbg_sseg_ctrl_cyc, wb_m2s_dbg_rgb_led_cyc, wb_m2s_dbg_ps2_0_cyc, wb_m2s_dbg_i2c_temp_cyc, wb_m2s_dbg_spi_flash_cyc, wb_m2s_dbg_spi_accel_cyc, wb_m2s_dbg_xadc0_cyc, wb_m2s_dbg_ddr2_cfg0_cyc}),
    .wbs_stb_o ({wb_m2s_dbg_ddr2_stb, wb_m2s_dbg_rom0_stb, wb_m2s_dbg_uart0_stb, wb_m2s_dbg_gpio_sw_stb, wb_m2s_dbg_gpio_pbtn_stb, wb_m2s_dbg_gpio_led_stb, wb_m2s_dbg_gpio_pmod_stb, wb_m2s_dbg_sseg_ctrl_stb, wb_m2s_dbg_rgb_led_stb, wb_m2s_dbg_ps2_0_stb, wb_m2s_dbg_i2c_temp_stb, wb_m2s_dbg_spi_flash_stb, wb_m2s_dbg_spi_accel_stb, wb_m2s_dbg_xadc0_stb, wb_m2s_dbg_ddr2_cfg0_stb}),
    .wbs_cti_o ({wb_m2s_dbg_ddr2_cti, wb_m2s_dbg_rom0_cti, wb_m2s_dbg_uart0_cti, wb_m2s_dbg_gpio_sw_cti, wb_m2s_dbg_gpio_pbtn_cti, wb_m2s_dbg_gpio_led_cti, wb_m2s_dbg_gpio_pmod_cti, wb_m2s_dbg_sseg_ctrl_cti, wb_m2s_dbg_rgb_led_cti, wb_m2s_dbg_ps2_0_cti, wb_m2s_dbg_i2c_temp_cti, wb_m2s_dbg_spi_flash_cti, wb_m2s_dbg_spi_accel_cti, wb_m2s_dbg_xadc0_cti, wb_m2s_dbg_ddr2_cfg0_cti}),
    .wbs_bte_o ({wb_m2s_dbg_ddr2_bte, wb_m2s_dbg_rom0_bte, wb_m2s_dbg_uart0_bte, wb_m2s_dbg_gpio_sw_bte, wb_m2s_dbg_gpio_pbtn_bte, wb_m2s_dbg_gpio_led_bte, wb_m2s_dbg_gpio_pmod_bte, wb_m2s_dbg_sseg_ctrl_bte, wb_m2s_dbg_rgb_led_bte, wb_m2s_dbg_ps2_0_bte, wb_m2s_dbg_i2c_temp_bte, wb_m2s_dbg_spi_flash_bte, wb_m2s_dbg_spi_accel_bte, wb_m2s_dbg_xadc0_bte, wb_m2s_dbg_ddr2_cfg0_bte}),
    .wbs_dat_i ({wb_s2m_dbg_ddr2_dat, wb_s2m_dbg_rom0_dat, wb_s2m_dbg_uart0_dat, wb_s2m_dbg_gpio_sw_dat, wb_s2m_dbg_gpio_pbtn_dat, wb_s2m_dbg_gpio_led_dat, wb_s2m_dbg_gpio_pmod_dat, wb_s2m_dbg_sseg_ctrl_dat, wb_s2m_dbg_rgb_led_dat, wb_s2m_dbg_ps2_0_dat, wb_s2m_dbg_i2c_temp_dat, wb_s2m_dbg_spi_flash_dat, wb_s2m_dbg_spi_accel_dat, wb_s2m_dbg_xadc0_dat, wb_s2m_dbg_ddr2_cfg0_dat}),
    .wbs_ack_i ({wb_s2m_dbg_ddr2_ack, wb_s2m_dbg_rom0_ack, wb_s2m_dbg_uart0_ack, wb_s2m_dbg_gpio_sw_ack, wb_s2m_dbg_gpio_pbtn_ack, wb_s2m_dbg_gpio_led_ack, wb_s2m_dbg_gpio_pmod_ack, wb_s2m_dbg_sseg_ctrl_ack, wb_s2m_dbg_rgb_led_ack, wb_s2m_dbg_ps2_0_ack, wb_s2m_dbg_i2c_temp_ack, wb_s2m_dbg_spi_flash_ack, wb_s2m_dbg_spi_accel_ack, wb_s2m_dbg_xadc0_ack, wb_s2m_dbg_ddr2_cfg0_ack}),
    .wbs_err_i ({wb_s2m_dbg_ddr2_err, wb_s2m_dbg_rom0_err, wb_s2m_dbg_uart0_err, wb_s2m_dbg_gpio_sw_err, wb_s2m_dbg_gpio_pbtn_err, wb_s2m_dbg_gpio_led_err, wb_s2m_dbg_gpio_pmod_err, wb_s2m_dbg_sseg_ctrl_err, wb_s2m_dbg_rgb_led_err, wb_s2m_dbg_ps2_0_err, wb_s2m_dbg_i2c_temp_err, wb_s2m_dbg_spi_flash_err, wb_s2m_dbg_spi_accel_err, wb_s2m_dbg_xadc0_err, wb_s2m_dbg_ddr2_cfg0_err}),
    .wbs_rty_i ({wb_s2m_dbg_ddr2_rty, wb_s2m_dbg_rom0_rty, wb_s2m_dbg_uart0_rty, wb_s2m_dbg_gpio_sw_rty, wb_s2m_dbg_gpio_pbtn_rty, wb_s2m_dbg_gpio_led_rty, wb_s2m_dbg_gpio_pmod_rty, wb_s2m_dbg_sseg_ctrl_rty, wb_s2m_dbg_rgb_led_rty, wb_s2m_dbg_ps2_0_rty, wb_s2m_dbg_i2c_temp_rty, wb_s2m_dbg_spi_flash_rty, wb_s2m_dbg_spi_accel_rty, wb_s2m_dbg_xadc0_rty, wb_s2m_dbg_ddr2_cfg0_rty}));

wb_mux
  #(.num_slaves (15),
    .MATCH_ADDR ({32'h00000000, 32'hf0000000, 32'h90000000, 32'h91000000, 32'h91001000, 32'h91002000, 32'h91003000, 32'h92000000, 32'h93000000, 32'h94000000, 32'hd0000000, 32'hb0000000, 32'hb1000000, 32'h95000000, 32'h96000000}),
    .MATCH_MASK ({32'hf8000000, 32'hfffffc00, 32'hffffffe0, 32'hfffffff8, 32'hfffffff8, 32'hfffffff8, 32'hfffffff8, 32'hffffffc0, 32'hfffffff0, 32'hfffffff8, 32'hfffffff8, 32'hfffffff8, 32'hfffffff8, 32'hfffffc00, 32'hfffffff0}))
 wb_mux_dbg_rs232
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_dbg_rs232_adr_i),
    .wbm_dat_i (wb_dbg_rs232_dat_i),
    .wbm_sel_i (wb_dbg_rs232_sel_i),
    .wbm_we_i  (wb_dbg_rs232_we_i),
    .wbm_cyc_i (wb_dbg_rs232_cyc_i),
    .wbm_stb_i (wb_dbg_rs232_stb_i),
    .wbm_cti_i (wb_dbg_rs232_cti_i),
    .wbm_bte_i (wb_dbg_rs232_bte_i),
    .wbm_dat_o (wb_dbg_rs232_dat_o),
    .wbm_ack_o (wb_dbg_rs232_ack_o),
    .wbm_err_o (wb_dbg_rs232_err_o),
    .wbm_rty_o (wb_dbg_rs232_rty_o),
    .wbs_adr_o ({wb_m2s_dbg_rs232_ddr2_adr, wb_m2s_dbg_rs232_rom0_adr, wb_m2s_dbg_rs232_uart0_adr, wb_m2s_dbg_rs232_gpio_sw_adr, wb_m2s_dbg_rs232_gpio_pbtn_adr, wb_m2s_dbg_rs232_gpio_led_adr, wb_m2s_dbg_rs232_gpio_pmod_adr, wb_m2s_dbg_rs232_sseg_ctrl_adr, wb_m2s_dbg_rs232_rgb_led_adr, wb_m2s_dbg_rs232_ps2_0_adr, wb_m2s_dbg_rs232_i2c_temp_adr, wb_m2s_dbg_rs232_spi_flash_adr, wb_m2s_dbg_rs232_spi_accel_adr, wb_m2s_dbg_rs232_xadc0_adr, wb_m2s_dbg_rs232_ddr2_cfg0_adr}),
    .wbs_dat_o ({wb_m2s_dbg_rs232_ddr2_dat, wb_m2s_dbg_rs232_rom0_dat, wb_m2s_dbg_rs232_uart0_dat, wb_m2s_dbg_rs232_gpio_sw_dat, wb_m2s_dbg_rs232_gpio_pbtn_dat, wb_m2s_dbg_rs232_gpio_led_dat, wb_m2s_dbg_rs232_gpio_pmod_dat, wb_m2s_dbg_rs232_sseg_ctrl_dat, wb_m2s_dbg_rs232_rgb_led_dat, wb_m2s_dbg_rs232_ps2_0_dat, wb_m2s_dbg_rs232_i2c_temp_dat, wb_m2s_dbg_rs232_spi_flash_dat, wb_m2s_dbg_rs232_spi_accel_dat, wb_m2s_dbg_rs232_xadc0_dat, wb_m2s_dbg_rs232_ddr2_cfg0_dat}),
    .wbs_sel_o ({wb_m2s_dbg_rs232_ddr2_sel, wb_m2s_dbg_rs232_rom0_sel, wb_m2s_dbg_rs232_uart0_sel, wb_m2s_dbg_rs232_gpio_sw_sel, wb_m2s_dbg_rs232_gpio_pbtn_sel, wb_m2s_dbg_rs232_gpio_led_sel, wb_m2s_dbg_rs232_gpio_pmod_sel, wb_m2s_dbg_rs232_sseg_ctrl_sel, wb_m2s_dbg_rs232_rgb_led_sel, wb_m2s_dbg_rs232_ps2_0_sel, wb_m2s_dbg_rs232_i2c_temp_sel, wb_m2s_dbg_rs232_spi_flash_sel, wb_m2s_dbg_rs232_spi_accel_sel, wb_m2s_dbg_rs232_xadc0_sel, wb_m2s_dbg_rs232_ddr2_cfg0_sel}),
    .wbs_we_o  ({wb_m2s_dbg_rs232_ddr2_we, wb_m2s_dbg_rs232_rom0_we, wb_m2s_dbg_rs232_uart0_we, wb_m2s_dbg_rs232_gpio_sw_we, wb_m2s_dbg_rs232_gpio_pbtn_we, wb_m2s_dbg_rs232_gpio_led_we, wb_m2s_dbg_rs232_gpio_pmod_we, wb_m2s_dbg_rs232_sseg_ctrl_we, wb_m2s_dbg_rs232_rgb_led_we, wb_m2s_dbg_rs232_ps2_0_we, wb_m2s_dbg_rs232_i2c_temp_we, wb_m2s_dbg_rs232_spi_flash_we, wb_m2s_dbg_rs232_spi_accel_we, wb_m2s_dbg_rs232_xadc0_we, wb_m2s_dbg_rs232_ddr2_cfg0_we}),
    .wbs_cyc_o ({wb_m2s_dbg_rs232_ddr2_cyc, wb_m2s_dbg_rs232_rom0_cyc, wb_m2s_dbg_rs232_uart0_cyc, wb_m2s_dbg_rs232_gpio_sw_cyc, wb_m2s_dbg_rs232_gpio_pbtn_cyc, wb_m2s_dbg_rs232_gpio_led_cyc, wb_m2s_dbg_rs232_gpio_pmod_cyc, wb_m2s_dbg_rs232_sseg_ctrl_cyc, wb_m2s_dbg_rs232_rgb_led_cyc, wb_m2s_dbg_rs232_ps2_0_cyc, wb_m2s_dbg_rs232_i2c_temp_cyc, wb_m2s_dbg_rs232_spi_flash_cyc, wb_m2s_dbg_rs232_spi_accel_cyc, wb_m2s_dbg_rs232_xadc0_cyc, wb_m2s_dbg_rs232_ddr2_cfg0_cyc}),
    .wbs_stb_o ({wb_m2s_dbg_rs232_ddr2_stb, wb_m2s_dbg_rs232_rom0_stb, wb_m2s_dbg_rs232_uart0_stb, wb_m2s_dbg_rs232_gpio_sw_stb, wb_m2s_dbg_rs232_gpio_pbtn_stb, wb_m2s_dbg_rs232_gpio_led_stb, wb_m2s_dbg_rs232_gpio_pmod_stb, wb_m2s_dbg_rs232_sseg_ctrl_stb, wb_m2s_dbg_rs232_rgb_led_stb, wb_m2s_dbg_rs232_ps2_0_stb, wb_m2s_dbg_rs232_i2c_temp_stb, wb_m2s_dbg_rs232_spi_flash_stb, wb_m2s_dbg_rs232_spi_accel_stb, wb_m2s_dbg_rs232_xadc0_stb, wb_m2s_dbg_rs232_ddr2_cfg0_stb}),
    .wbs_cti_o ({wb_m2s_dbg_rs232_ddr2_cti, wb_m2s_dbg_rs232_rom0_cti, wb_m2s_dbg_rs232_uart0_cti, wb_m2s_dbg_rs232_gpio_sw_cti, wb_m2s_dbg_rs232_gpio_pbtn_cti, wb_m2s_dbg_rs232_gpio_led_cti, wb_m2s_dbg_rs232_gpio_pmod_cti, wb_m2s_dbg_rs232_sseg_ctrl_cti, wb_m2s_dbg_rs232_rgb_led_cti, wb_m2s_dbg_rs232_ps2_0_cti, wb_m2s_dbg_rs232_i2c_temp_cti, wb_m2s_dbg_rs232_spi_flash_cti, wb_m2s_dbg_rs232_spi_accel_cti, wb_m2s_dbg_rs232_xadc0_cti, wb_m2s_dbg_rs232_ddr2_cfg0_cti}),
    .wbs_bte_o ({wb_m2s_dbg_rs232_ddr2_bte, wb_m2s_dbg_rs232_rom0_bte, wb_m2s_dbg_rs232_uart0_bte, wb_m2s_dbg_rs232_gpio_sw_bte, wb_m2s_dbg_rs232_gpio_pbtn_bte, wb_m2s_dbg_rs232_gpio_led_bte, wb_m2s_dbg_rs232_gpio_pmod_bte, wb_m2s_dbg_rs232_sseg_ctrl_bte, wb_m2s_dbg_rs232_rgb_led_bte, wb_m2s_dbg_rs232_ps2_0_bte, wb_m2s_dbg_rs232_i2c_temp_bte, wb_m2s_dbg_rs232_spi_flash_bte, wb_m2s_dbg_rs232_spi_accel_bte, wb_m2s_dbg_rs232_xadc0_bte, wb_m2s_dbg_rs232_ddr2_cfg0_bte}),
    .wbs_dat_i ({wb_s2m_dbg_rs232_ddr2_dat, wb_s2m_dbg_rs232_rom0_dat, wb_s2m_dbg_rs232_uart0_dat, wb_s2m_dbg_rs232_gpio_sw_dat, wb_s2m_dbg_rs232_gpio_pbtn_dat, wb_s2m_dbg_rs232_gpio_led_dat, wb_s2m_dbg_rs232_gpio_pmod_dat, wb_s2m_dbg_rs232_sseg_ctrl_dat, wb_s2m_dbg_rs232_rgb_led_dat, wb_s2m_dbg_rs232_ps2_0_dat, wb_s2m_dbg_rs232_i2c_temp_dat, wb_s2m_dbg_rs232_spi_flash_dat, wb_s2m_dbg_rs232_spi_accel_dat, wb_s2m_dbg_rs232_xadc0_dat, wb_s2m_dbg_rs232_ddr2_cfg0_dat}),
    .wbs_ack_i ({wb_s2m_dbg_rs232_ddr2_ack, wb_s2m_dbg_rs232_rom0_ack, wb_s2m_dbg_rs232_uart0_ack, wb_s2m_dbg_rs232_gpio_sw_ack, wb_s2m_dbg_rs232_gpio_pbtn_ack, wb_s2m_dbg_rs232_gpio_led_ack, wb_s2m_dbg_rs232_gpio_pmod_ack, wb_s2m_dbg_rs232_sseg_ctrl_ack, wb_s2m_dbg_rs232_rgb_led_ack, wb_s2m_dbg_rs232_ps2_0_ack, wb_s2m_dbg_rs232_i2c_temp_ack, wb_s2m_dbg_rs232_spi_flash_ack, wb_s2m_dbg_rs232_spi_accel_ack, wb_s2m_dbg_rs232_xadc0_ack, wb_s2m_dbg_rs232_ddr2_cfg0_ack}),
    .wbs_err_i ({wb_s2m_dbg_rs232_ddr2_err, wb_s2m_dbg_rs232_rom0_err, wb_s2m_dbg_rs232_uart0_err, wb_s2m_dbg_rs232_gpio_sw_err, wb_s2m_dbg_rs232_gpio_pbtn_err, wb_s2m_dbg_rs232_gpio_led_err, wb_s2m_dbg_rs232_gpio_pmod_err, wb_s2m_dbg_rs232_sseg_ctrl_err, wb_s2m_dbg_rs232_rgb_led_err, wb_s2m_dbg_rs232_ps2_0_err, wb_s2m_dbg_rs232_i2c_temp_err, wb_s2m_dbg_rs232_spi_flash_err, wb_s2m_dbg_rs232_spi_accel_err, wb_s2m_dbg_rs232_xadc0_err, wb_s2m_dbg_rs232_ddr2_cfg0_err}),
    .wbs_rty_i ({wb_s2m_dbg_rs232_ddr2_rty, wb_s2m_dbg_rs232_rom0_rty, wb_s2m_dbg_rs232_uart0_rty, wb_s2m_dbg_rs232_gpio_sw_rty, wb_s2m_dbg_rs232_gpio_pbtn_rty, wb_s2m_dbg_rs232_gpio_led_rty, wb_s2m_dbg_rs232_gpio_pmod_rty, wb_s2m_dbg_rs232_sseg_ctrl_rty, wb_s2m_dbg_rs232_rgb_led_rty, wb_s2m_dbg_rs232_ps2_0_rty, wb_s2m_dbg_rs232_i2c_temp_rty, wb_s2m_dbg_rs232_spi_flash_rty, wb_s2m_dbg_rs232_spi_accel_rty, wb_s2m_dbg_rs232_xadc0_rty, wb_s2m_dbg_rs232_ddr2_cfg0_rty}));

wb_arbiter
  #(.num_masters (4))
 wb_arbiter_ddr2
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_i_ddr2_adr, wb_m2s_or1k_d_ddr2_adr, wb_m2s_dbg_ddr2_adr, wb_m2s_dbg_rs232_ddr2_adr}),
    .wbm_dat_i ({wb_m2s_or1k_i_ddr2_dat, wb_m2s_or1k_d_ddr2_dat, wb_m2s_dbg_ddr2_dat, wb_m2s_dbg_rs232_ddr2_dat}),
    .wbm_sel_i ({wb_m2s_or1k_i_ddr2_sel, wb_m2s_or1k_d_ddr2_sel, wb_m2s_dbg_ddr2_sel, wb_m2s_dbg_rs232_ddr2_sel}),
    .wbm_we_i  ({wb_m2s_or1k_i_ddr2_we, wb_m2s_or1k_d_ddr2_we, wb_m2s_dbg_ddr2_we, wb_m2s_dbg_rs232_ddr2_we}),
    .wbm_cyc_i ({wb_m2s_or1k_i_ddr2_cyc, wb_m2s_or1k_d_ddr2_cyc, wb_m2s_dbg_ddr2_cyc, wb_m2s_dbg_rs232_ddr2_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_i_ddr2_stb, wb_m2s_or1k_d_ddr2_stb, wb_m2s_dbg_ddr2_stb, wb_m2s_dbg_rs232_ddr2_stb}),
    .wbm_cti_i ({wb_m2s_or1k_i_ddr2_cti, wb_m2s_or1k_d_ddr2_cti, wb_m2s_dbg_ddr2_cti, wb_m2s_dbg_rs232_ddr2_cti}),
    .wbm_bte_i ({wb_m2s_or1k_i_ddr2_bte, wb_m2s_or1k_d_ddr2_bte, wb_m2s_dbg_ddr2_bte, wb_m2s_dbg_rs232_ddr2_bte}),
    .wbm_dat_o ({wb_s2m_or1k_i_ddr2_dat, wb_s2m_or1k_d_ddr2_dat, wb_s2m_dbg_ddr2_dat, wb_s2m_dbg_rs232_ddr2_dat}),
    .wbm_ack_o ({wb_s2m_or1k_i_ddr2_ack, wb_s2m_or1k_d_ddr2_ack, wb_s2m_dbg_ddr2_ack, wb_s2m_dbg_rs232_ddr2_ack}),
    .wbm_err_o ({wb_s2m_or1k_i_ddr2_err, wb_s2m_or1k_d_ddr2_err, wb_s2m_dbg_ddr2_err, wb_s2m_dbg_rs232_ddr2_err}),
    .wbm_rty_o ({wb_s2m_or1k_i_ddr2_rty, wb_s2m_or1k_d_ddr2_rty, wb_s2m_dbg_ddr2_rty, wb_s2m_dbg_rs232_ddr2_rty}),
    .wbs_adr_o (wb_ddr2_adr_o),
    .wbs_dat_o (wb_ddr2_dat_o),
    .wbs_sel_o (wb_ddr2_sel_o),
    .wbs_we_o  (wb_ddr2_we_o),
    .wbs_cyc_o (wb_ddr2_cyc_o),
    .wbs_stb_o (wb_ddr2_stb_o),
    .wbs_cti_o (wb_ddr2_cti_o),
    .wbs_bte_o (wb_ddr2_bte_o),
    .wbs_dat_i (wb_ddr2_dat_i),
    .wbs_ack_i (wb_ddr2_ack_i),
    .wbs_err_i (wb_ddr2_err_i),
    .wbs_rty_i (wb_ddr2_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_uart0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_uart0_adr, wb_m2s_dbg_uart0_adr, wb_m2s_dbg_rs232_uart0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_uart0_dat, wb_m2s_dbg_uart0_dat, wb_m2s_dbg_rs232_uart0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_uart0_sel, wb_m2s_dbg_uart0_sel, wb_m2s_dbg_rs232_uart0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_uart0_we, wb_m2s_dbg_uart0_we, wb_m2s_dbg_rs232_uart0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_uart0_cyc, wb_m2s_dbg_uart0_cyc, wb_m2s_dbg_rs232_uart0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_uart0_stb, wb_m2s_dbg_uart0_stb, wb_m2s_dbg_rs232_uart0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_uart0_cti, wb_m2s_dbg_uart0_cti, wb_m2s_dbg_rs232_uart0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_uart0_bte, wb_m2s_dbg_uart0_bte, wb_m2s_dbg_rs232_uart0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_uart0_dat, wb_s2m_dbg_uart0_dat, wb_s2m_dbg_rs232_uart0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_uart0_ack, wb_s2m_dbg_uart0_ack, wb_s2m_dbg_rs232_uart0_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_uart0_err, wb_s2m_dbg_uart0_err, wb_s2m_dbg_rs232_uart0_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_uart0_rty, wb_s2m_dbg_uart0_rty, wb_s2m_dbg_rs232_uart0_rty}),
    .wbs_adr_o (wb_m2s_resize_uart0_adr),
    .wbs_dat_o (wb_m2s_resize_uart0_dat),
    .wbs_sel_o (wb_m2s_resize_uart0_sel),
    .wbs_we_o  (wb_m2s_resize_uart0_we),
    .wbs_cyc_o (wb_m2s_resize_uart0_cyc),
    .wbs_stb_o (wb_m2s_resize_uart0_stb),
    .wbs_cti_o (wb_m2s_resize_uart0_cti),
    .wbs_bte_o (wb_m2s_resize_uart0_bte),
    .wbs_dat_i (wb_s2m_resize_uart0_dat),
    .wbs_ack_i (wb_s2m_resize_uart0_ack),
    .wbs_err_i (wb_s2m_resize_uart0_err),
    .wbs_rty_i (wb_s2m_resize_uart0_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_uart0
   (.wbm_adr_i (wb_m2s_resize_uart0_adr),
    .wbm_dat_i (wb_m2s_resize_uart0_dat),
    .wbm_sel_i (wb_m2s_resize_uart0_sel),
    .wbm_we_i  (wb_m2s_resize_uart0_we),
    .wbm_cyc_i (wb_m2s_resize_uart0_cyc),
    .wbm_stb_i (wb_m2s_resize_uart0_stb),
    .wbm_cti_i (wb_m2s_resize_uart0_cti),
    .wbm_bte_i (wb_m2s_resize_uart0_bte),
    .wbm_dat_o (wb_s2m_resize_uart0_dat),
    .wbm_ack_o (wb_s2m_resize_uart0_ack),
    .wbm_err_o (wb_s2m_resize_uart0_err),
    .wbm_rty_o (wb_s2m_resize_uart0_rty),
    .wbs_adr_o (wb_uart0_adr_o),
    .wbs_dat_o (wb_uart0_dat_o),
    .wbs_we_o  (wb_uart0_we_o),
    .wbs_cyc_o (wb_uart0_cyc_o),
    .wbs_stb_o (wb_uart0_stb_o),
    .wbs_cti_o (wb_uart0_cti_o),
    .wbs_bte_o (wb_uart0_bte_o),
    .wbs_dat_i (wb_uart0_dat_i),
    .wbs_ack_i (wb_uart0_ack_i),
    .wbs_err_i (wb_uart0_err_i),
    .wbs_rty_i (wb_uart0_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_gpio_sw
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_gpio_sw_adr, wb_m2s_dbg_gpio_sw_adr, wb_m2s_dbg_rs232_gpio_sw_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_gpio_sw_dat, wb_m2s_dbg_gpio_sw_dat, wb_m2s_dbg_rs232_gpio_sw_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_gpio_sw_sel, wb_m2s_dbg_gpio_sw_sel, wb_m2s_dbg_rs232_gpio_sw_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_gpio_sw_we, wb_m2s_dbg_gpio_sw_we, wb_m2s_dbg_rs232_gpio_sw_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_gpio_sw_cyc, wb_m2s_dbg_gpio_sw_cyc, wb_m2s_dbg_rs232_gpio_sw_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_gpio_sw_stb, wb_m2s_dbg_gpio_sw_stb, wb_m2s_dbg_rs232_gpio_sw_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_gpio_sw_cti, wb_m2s_dbg_gpio_sw_cti, wb_m2s_dbg_rs232_gpio_sw_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_gpio_sw_bte, wb_m2s_dbg_gpio_sw_bte, wb_m2s_dbg_rs232_gpio_sw_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_gpio_sw_dat, wb_s2m_dbg_gpio_sw_dat, wb_s2m_dbg_rs232_gpio_sw_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_gpio_sw_ack, wb_s2m_dbg_gpio_sw_ack, wb_s2m_dbg_rs232_gpio_sw_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_gpio_sw_err, wb_s2m_dbg_gpio_sw_err, wb_s2m_dbg_rs232_gpio_sw_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_gpio_sw_rty, wb_s2m_dbg_gpio_sw_rty, wb_s2m_dbg_rs232_gpio_sw_rty}),
    .wbs_adr_o (wb_m2s_resize_gpio_sw_adr),
    .wbs_dat_o (wb_m2s_resize_gpio_sw_dat),
    .wbs_sel_o (wb_m2s_resize_gpio_sw_sel),
    .wbs_we_o  (wb_m2s_resize_gpio_sw_we),
    .wbs_cyc_o (wb_m2s_resize_gpio_sw_cyc),
    .wbs_stb_o (wb_m2s_resize_gpio_sw_stb),
    .wbs_cti_o (wb_m2s_resize_gpio_sw_cti),
    .wbs_bte_o (wb_m2s_resize_gpio_sw_bte),
    .wbs_dat_i (wb_s2m_resize_gpio_sw_dat),
    .wbs_ack_i (wb_s2m_resize_gpio_sw_ack),
    .wbs_err_i (wb_s2m_resize_gpio_sw_err),
    .wbs_rty_i (wb_s2m_resize_gpio_sw_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (16))
 wb_data_resize_gpio_sw
   (.wbm_adr_i (wb_m2s_resize_gpio_sw_adr),
    .wbm_dat_i (wb_m2s_resize_gpio_sw_dat),
    .wbm_sel_i (wb_m2s_resize_gpio_sw_sel),
    .wbm_we_i  (wb_m2s_resize_gpio_sw_we),
    .wbm_cyc_i (wb_m2s_resize_gpio_sw_cyc),
    .wbm_stb_i (wb_m2s_resize_gpio_sw_stb),
    .wbm_cti_i (wb_m2s_resize_gpio_sw_cti),
    .wbm_bte_i (wb_m2s_resize_gpio_sw_bte),
    .wbm_dat_o (wb_s2m_resize_gpio_sw_dat),
    .wbm_ack_o (wb_s2m_resize_gpio_sw_ack),
    .wbm_err_o (wb_s2m_resize_gpio_sw_err),
    .wbm_rty_o (wb_s2m_resize_gpio_sw_rty),
    .wbs_adr_o (wb_gpio_sw_adr_o),
    .wbs_dat_o (wb_gpio_sw_dat_o),
    .wbs_we_o  (wb_gpio_sw_we_o),
    .wbs_cyc_o (wb_gpio_sw_cyc_o),
    .wbs_stb_o (wb_gpio_sw_stb_o),
    .wbs_cti_o (wb_gpio_sw_cti_o),
    .wbs_bte_o (wb_gpio_sw_bte_o),
    .wbs_dat_i (wb_gpio_sw_dat_i),
    .wbs_ack_i (wb_gpio_sw_ack_i),
    .wbs_err_i (wb_gpio_sw_err_i),
    .wbs_rty_i (wb_gpio_sw_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_gpio_pbtn
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_gpio_pbtn_adr, wb_m2s_dbg_gpio_pbtn_adr, wb_m2s_dbg_rs232_gpio_pbtn_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_gpio_pbtn_dat, wb_m2s_dbg_gpio_pbtn_dat, wb_m2s_dbg_rs232_gpio_pbtn_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_gpio_pbtn_sel, wb_m2s_dbg_gpio_pbtn_sel, wb_m2s_dbg_rs232_gpio_pbtn_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_gpio_pbtn_we, wb_m2s_dbg_gpio_pbtn_we, wb_m2s_dbg_rs232_gpio_pbtn_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_gpio_pbtn_cyc, wb_m2s_dbg_gpio_pbtn_cyc, wb_m2s_dbg_rs232_gpio_pbtn_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_gpio_pbtn_stb, wb_m2s_dbg_gpio_pbtn_stb, wb_m2s_dbg_rs232_gpio_pbtn_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_gpio_pbtn_cti, wb_m2s_dbg_gpio_pbtn_cti, wb_m2s_dbg_rs232_gpio_pbtn_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_gpio_pbtn_bte, wb_m2s_dbg_gpio_pbtn_bte, wb_m2s_dbg_rs232_gpio_pbtn_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_gpio_pbtn_dat, wb_s2m_dbg_gpio_pbtn_dat, wb_s2m_dbg_rs232_gpio_pbtn_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_gpio_pbtn_ack, wb_s2m_dbg_gpio_pbtn_ack, wb_s2m_dbg_rs232_gpio_pbtn_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_gpio_pbtn_err, wb_s2m_dbg_gpio_pbtn_err, wb_s2m_dbg_rs232_gpio_pbtn_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_gpio_pbtn_rty, wb_s2m_dbg_gpio_pbtn_rty, wb_s2m_dbg_rs232_gpio_pbtn_rty}),
    .wbs_adr_o (wb_m2s_resize_gpio_pbtn_adr),
    .wbs_dat_o (wb_m2s_resize_gpio_pbtn_dat),
    .wbs_sel_o (wb_m2s_resize_gpio_pbtn_sel),
    .wbs_we_o  (wb_m2s_resize_gpio_pbtn_we),
    .wbs_cyc_o (wb_m2s_resize_gpio_pbtn_cyc),
    .wbs_stb_o (wb_m2s_resize_gpio_pbtn_stb),
    .wbs_cti_o (wb_m2s_resize_gpio_pbtn_cti),
    .wbs_bte_o (wb_m2s_resize_gpio_pbtn_bte),
    .wbs_dat_i (wb_s2m_resize_gpio_pbtn_dat),
    .wbs_ack_i (wb_s2m_resize_gpio_pbtn_ack),
    .wbs_err_i (wb_s2m_resize_gpio_pbtn_err),
    .wbs_rty_i (wb_s2m_resize_gpio_pbtn_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (5))
 wb_data_resize_gpio_pbtn
   (.wbm_adr_i (wb_m2s_resize_gpio_pbtn_adr),
    .wbm_dat_i (wb_m2s_resize_gpio_pbtn_dat),
    .wbm_sel_i (wb_m2s_resize_gpio_pbtn_sel),
    .wbm_we_i  (wb_m2s_resize_gpio_pbtn_we),
    .wbm_cyc_i (wb_m2s_resize_gpio_pbtn_cyc),
    .wbm_stb_i (wb_m2s_resize_gpio_pbtn_stb),
    .wbm_cti_i (wb_m2s_resize_gpio_pbtn_cti),
    .wbm_bte_i (wb_m2s_resize_gpio_pbtn_bte),
    .wbm_dat_o (wb_s2m_resize_gpio_pbtn_dat),
    .wbm_ack_o (wb_s2m_resize_gpio_pbtn_ack),
    .wbm_err_o (wb_s2m_resize_gpio_pbtn_err),
    .wbm_rty_o (wb_s2m_resize_gpio_pbtn_rty),
    .wbs_adr_o (wb_gpio_pbtn_adr_o),
    .wbs_dat_o (wb_gpio_pbtn_dat_o),
    .wbs_we_o  (wb_gpio_pbtn_we_o),
    .wbs_cyc_o (wb_gpio_pbtn_cyc_o),
    .wbs_stb_o (wb_gpio_pbtn_stb_o),
    .wbs_cti_o (wb_gpio_pbtn_cti_o),
    .wbs_bte_o (wb_gpio_pbtn_bte_o),
    .wbs_dat_i (wb_gpio_pbtn_dat_i),
    .wbs_ack_i (wb_gpio_pbtn_ack_i),
    .wbs_err_i (wb_gpio_pbtn_err_i),
    .wbs_rty_i (wb_gpio_pbtn_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_gpio_led
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_gpio_led_adr, wb_m2s_dbg_gpio_led_adr, wb_m2s_dbg_rs232_gpio_led_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_gpio_led_dat, wb_m2s_dbg_gpio_led_dat, wb_m2s_dbg_rs232_gpio_led_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_gpio_led_sel, wb_m2s_dbg_gpio_led_sel, wb_m2s_dbg_rs232_gpio_led_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_gpio_led_we, wb_m2s_dbg_gpio_led_we, wb_m2s_dbg_rs232_gpio_led_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_gpio_led_cyc, wb_m2s_dbg_gpio_led_cyc, wb_m2s_dbg_rs232_gpio_led_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_gpio_led_stb, wb_m2s_dbg_gpio_led_stb, wb_m2s_dbg_rs232_gpio_led_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_gpio_led_cti, wb_m2s_dbg_gpio_led_cti, wb_m2s_dbg_rs232_gpio_led_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_gpio_led_bte, wb_m2s_dbg_gpio_led_bte, wb_m2s_dbg_rs232_gpio_led_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_gpio_led_dat, wb_s2m_dbg_gpio_led_dat, wb_s2m_dbg_rs232_gpio_led_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_gpio_led_ack, wb_s2m_dbg_gpio_led_ack, wb_s2m_dbg_rs232_gpio_led_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_gpio_led_err, wb_s2m_dbg_gpio_led_err, wb_s2m_dbg_rs232_gpio_led_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_gpio_led_rty, wb_s2m_dbg_gpio_led_rty, wb_s2m_dbg_rs232_gpio_led_rty}),
    .wbs_adr_o (wb_m2s_resize_gpio_led_adr),
    .wbs_dat_o (wb_m2s_resize_gpio_led_dat),
    .wbs_sel_o (wb_m2s_resize_gpio_led_sel),
    .wbs_we_o  (wb_m2s_resize_gpio_led_we),
    .wbs_cyc_o (wb_m2s_resize_gpio_led_cyc),
    .wbs_stb_o (wb_m2s_resize_gpio_led_stb),
    .wbs_cti_o (wb_m2s_resize_gpio_led_cti),
    .wbs_bte_o (wb_m2s_resize_gpio_led_bte),
    .wbs_dat_i (wb_s2m_resize_gpio_led_dat),
    .wbs_ack_i (wb_s2m_resize_gpio_led_ack),
    .wbs_err_i (wb_s2m_resize_gpio_led_err),
    .wbs_rty_i (wb_s2m_resize_gpio_led_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (16))
 wb_data_resize_gpio_led
   (.wbm_adr_i (wb_m2s_resize_gpio_led_adr),
    .wbm_dat_i (wb_m2s_resize_gpio_led_dat),
    .wbm_sel_i (wb_m2s_resize_gpio_led_sel),
    .wbm_we_i  (wb_m2s_resize_gpio_led_we),
    .wbm_cyc_i (wb_m2s_resize_gpio_led_cyc),
    .wbm_stb_i (wb_m2s_resize_gpio_led_stb),
    .wbm_cti_i (wb_m2s_resize_gpio_led_cti),
    .wbm_bte_i (wb_m2s_resize_gpio_led_bte),
    .wbm_dat_o (wb_s2m_resize_gpio_led_dat),
    .wbm_ack_o (wb_s2m_resize_gpio_led_ack),
    .wbm_err_o (wb_s2m_resize_gpio_led_err),
    .wbm_rty_o (wb_s2m_resize_gpio_led_rty),
    .wbs_adr_o (wb_gpio_led_adr_o),
    .wbs_dat_o (wb_gpio_led_dat_o),
    .wbs_we_o  (wb_gpio_led_we_o),
    .wbs_cyc_o (wb_gpio_led_cyc_o),
    .wbs_stb_o (wb_gpio_led_stb_o),
    .wbs_cti_o (wb_gpio_led_cti_o),
    .wbs_bte_o (wb_gpio_led_bte_o),
    .wbs_dat_i (wb_gpio_led_dat_i),
    .wbs_ack_i (wb_gpio_led_ack_i),
    .wbs_err_i (wb_gpio_led_err_i),
    .wbs_rty_i (wb_gpio_led_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_gpio_pmod
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_gpio_pmod_adr, wb_m2s_dbg_gpio_pmod_adr, wb_m2s_dbg_rs232_gpio_pmod_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_gpio_pmod_dat, wb_m2s_dbg_gpio_pmod_dat, wb_m2s_dbg_rs232_gpio_pmod_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_gpio_pmod_sel, wb_m2s_dbg_gpio_pmod_sel, wb_m2s_dbg_rs232_gpio_pmod_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_gpio_pmod_we, wb_m2s_dbg_gpio_pmod_we, wb_m2s_dbg_rs232_gpio_pmod_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_gpio_pmod_cyc, wb_m2s_dbg_gpio_pmod_cyc, wb_m2s_dbg_rs232_gpio_pmod_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_gpio_pmod_stb, wb_m2s_dbg_gpio_pmod_stb, wb_m2s_dbg_rs232_gpio_pmod_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_gpio_pmod_cti, wb_m2s_dbg_gpio_pmod_cti, wb_m2s_dbg_rs232_gpio_pmod_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_gpio_pmod_bte, wb_m2s_dbg_gpio_pmod_bte, wb_m2s_dbg_rs232_gpio_pmod_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_gpio_pmod_dat, wb_s2m_dbg_gpio_pmod_dat, wb_s2m_dbg_rs232_gpio_pmod_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_gpio_pmod_ack, wb_s2m_dbg_gpio_pmod_ack, wb_s2m_dbg_rs232_gpio_pmod_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_gpio_pmod_err, wb_s2m_dbg_gpio_pmod_err, wb_s2m_dbg_rs232_gpio_pmod_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_gpio_pmod_rty, wb_s2m_dbg_gpio_pmod_rty, wb_s2m_dbg_rs232_gpio_pmod_rty}),
    .wbs_adr_o (wb_gpio_pmod_adr_o),
    .wbs_dat_o (wb_gpio_pmod_dat_o),
    .wbs_sel_o (wb_gpio_pmod_sel_o),
    .wbs_we_o  (wb_gpio_pmod_we_o),
    .wbs_cyc_o (wb_gpio_pmod_cyc_o),
    .wbs_stb_o (wb_gpio_pmod_stb_o),
    .wbs_cti_o (wb_gpio_pmod_cti_o),
    .wbs_bte_o (wb_gpio_pmod_bte_o),
    .wbs_dat_i (wb_gpio_pmod_dat_i),
    .wbs_ack_i (wb_gpio_pmod_ack_i),
    .wbs_err_i (wb_gpio_pmod_err_i),
    .wbs_rty_i (wb_gpio_pmod_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_sseg_ctrl
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_sseg_ctrl_adr, wb_m2s_dbg_sseg_ctrl_adr, wb_m2s_dbg_rs232_sseg_ctrl_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_sseg_ctrl_dat, wb_m2s_dbg_sseg_ctrl_dat, wb_m2s_dbg_rs232_sseg_ctrl_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_sseg_ctrl_sel, wb_m2s_dbg_sseg_ctrl_sel, wb_m2s_dbg_rs232_sseg_ctrl_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_sseg_ctrl_we, wb_m2s_dbg_sseg_ctrl_we, wb_m2s_dbg_rs232_sseg_ctrl_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_sseg_ctrl_cyc, wb_m2s_dbg_sseg_ctrl_cyc, wb_m2s_dbg_rs232_sseg_ctrl_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_sseg_ctrl_stb, wb_m2s_dbg_sseg_ctrl_stb, wb_m2s_dbg_rs232_sseg_ctrl_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_sseg_ctrl_cti, wb_m2s_dbg_sseg_ctrl_cti, wb_m2s_dbg_rs232_sseg_ctrl_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_sseg_ctrl_bte, wb_m2s_dbg_sseg_ctrl_bte, wb_m2s_dbg_rs232_sseg_ctrl_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_sseg_ctrl_dat, wb_s2m_dbg_sseg_ctrl_dat, wb_s2m_dbg_rs232_sseg_ctrl_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_sseg_ctrl_ack, wb_s2m_dbg_sseg_ctrl_ack, wb_s2m_dbg_rs232_sseg_ctrl_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_sseg_ctrl_err, wb_s2m_dbg_sseg_ctrl_err, wb_s2m_dbg_rs232_sseg_ctrl_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_sseg_ctrl_rty, wb_s2m_dbg_sseg_ctrl_rty, wb_s2m_dbg_rs232_sseg_ctrl_rty}),
    .wbs_adr_o (wb_m2s_resize_sseg_ctrl_adr),
    .wbs_dat_o (wb_m2s_resize_sseg_ctrl_dat),
    .wbs_sel_o (wb_m2s_resize_sseg_ctrl_sel),
    .wbs_we_o  (wb_m2s_resize_sseg_ctrl_we),
    .wbs_cyc_o (wb_m2s_resize_sseg_ctrl_cyc),
    .wbs_stb_o (wb_m2s_resize_sseg_ctrl_stb),
    .wbs_cti_o (wb_m2s_resize_sseg_ctrl_cti),
    .wbs_bte_o (wb_m2s_resize_sseg_ctrl_bte),
    .wbs_dat_i (wb_s2m_resize_sseg_ctrl_dat),
    .wbs_ack_i (wb_s2m_resize_sseg_ctrl_ack),
    .wbs_err_i (wb_s2m_resize_sseg_ctrl_err),
    .wbs_rty_i (wb_s2m_resize_sseg_ctrl_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (16))
 wb_data_resize_sseg_ctrl
   (.wbm_adr_i (wb_m2s_resize_sseg_ctrl_adr),
    .wbm_dat_i (wb_m2s_resize_sseg_ctrl_dat),
    .wbm_sel_i (wb_m2s_resize_sseg_ctrl_sel),
    .wbm_we_i  (wb_m2s_resize_sseg_ctrl_we),
    .wbm_cyc_i (wb_m2s_resize_sseg_ctrl_cyc),
    .wbm_stb_i (wb_m2s_resize_sseg_ctrl_stb),
    .wbm_cti_i (wb_m2s_resize_sseg_ctrl_cti),
    .wbm_bte_i (wb_m2s_resize_sseg_ctrl_bte),
    .wbm_dat_o (wb_s2m_resize_sseg_ctrl_dat),
    .wbm_ack_o (wb_s2m_resize_sseg_ctrl_ack),
    .wbm_err_o (wb_s2m_resize_sseg_ctrl_err),
    .wbm_rty_o (wb_s2m_resize_sseg_ctrl_rty),
    .wbs_adr_o (wb_sseg_ctrl_adr_o),
    .wbs_dat_o (wb_sseg_ctrl_dat_o),
    .wbs_we_o  (wb_sseg_ctrl_we_o),
    .wbs_cyc_o (wb_sseg_ctrl_cyc_o),
    .wbs_stb_o (wb_sseg_ctrl_stb_o),
    .wbs_cti_o (wb_sseg_ctrl_cti_o),
    .wbs_bte_o (wb_sseg_ctrl_bte_o),
    .wbs_dat_i (wb_sseg_ctrl_dat_i),
    .wbs_ack_i (wb_sseg_ctrl_ack_i),
    .wbs_err_i (wb_sseg_ctrl_err_i),
    .wbs_rty_i (wb_sseg_ctrl_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_rgb_led
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_rgb_led_adr, wb_m2s_dbg_rgb_led_adr, wb_m2s_dbg_rs232_rgb_led_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_rgb_led_dat, wb_m2s_dbg_rgb_led_dat, wb_m2s_dbg_rs232_rgb_led_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_rgb_led_sel, wb_m2s_dbg_rgb_led_sel, wb_m2s_dbg_rs232_rgb_led_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_rgb_led_we, wb_m2s_dbg_rgb_led_we, wb_m2s_dbg_rs232_rgb_led_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_rgb_led_cyc, wb_m2s_dbg_rgb_led_cyc, wb_m2s_dbg_rs232_rgb_led_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_rgb_led_stb, wb_m2s_dbg_rgb_led_stb, wb_m2s_dbg_rs232_rgb_led_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_rgb_led_cti, wb_m2s_dbg_rgb_led_cti, wb_m2s_dbg_rs232_rgb_led_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_rgb_led_bte, wb_m2s_dbg_rgb_led_bte, wb_m2s_dbg_rs232_rgb_led_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_rgb_led_dat, wb_s2m_dbg_rgb_led_dat, wb_s2m_dbg_rs232_rgb_led_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_rgb_led_ack, wb_s2m_dbg_rgb_led_ack, wb_s2m_dbg_rs232_rgb_led_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_rgb_led_err, wb_s2m_dbg_rgb_led_err, wb_s2m_dbg_rs232_rgb_led_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_rgb_led_rty, wb_s2m_dbg_rgb_led_rty, wb_s2m_dbg_rs232_rgb_led_rty}),
    .wbs_adr_o (wb_m2s_resize_rgb_led_adr),
    .wbs_dat_o (wb_m2s_resize_rgb_led_dat),
    .wbs_sel_o (wb_m2s_resize_rgb_led_sel),
    .wbs_we_o  (wb_m2s_resize_rgb_led_we),
    .wbs_cyc_o (wb_m2s_resize_rgb_led_cyc),
    .wbs_stb_o (wb_m2s_resize_rgb_led_stb),
    .wbs_cti_o (wb_m2s_resize_rgb_led_cti),
    .wbs_bte_o (wb_m2s_resize_rgb_led_bte),
    .wbs_dat_i (wb_s2m_resize_rgb_led_dat),
    .wbs_ack_i (wb_s2m_resize_rgb_led_ack),
    .wbs_err_i (wb_s2m_resize_rgb_led_err),
    .wbs_rty_i (wb_s2m_resize_rgb_led_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (24))
 wb_data_resize_rgb_led
   (.wbm_adr_i (wb_m2s_resize_rgb_led_adr),
    .wbm_dat_i (wb_m2s_resize_rgb_led_dat),
    .wbm_sel_i (wb_m2s_resize_rgb_led_sel),
    .wbm_we_i  (wb_m2s_resize_rgb_led_we),
    .wbm_cyc_i (wb_m2s_resize_rgb_led_cyc),
    .wbm_stb_i (wb_m2s_resize_rgb_led_stb),
    .wbm_cti_i (wb_m2s_resize_rgb_led_cti),
    .wbm_bte_i (wb_m2s_resize_rgb_led_bte),
    .wbm_dat_o (wb_s2m_resize_rgb_led_dat),
    .wbm_ack_o (wb_s2m_resize_rgb_led_ack),
    .wbm_err_o (wb_s2m_resize_rgb_led_err),
    .wbm_rty_o (wb_s2m_resize_rgb_led_rty),
    .wbs_adr_o (wb_rgb_led_adr_o),
    .wbs_dat_o (wb_rgb_led_dat_o),
    .wbs_we_o  (wb_rgb_led_we_o),
    .wbs_cyc_o (wb_rgb_led_cyc_o),
    .wbs_stb_o (wb_rgb_led_stb_o),
    .wbs_cti_o (wb_rgb_led_cti_o),
    .wbs_bte_o (wb_rgb_led_bte_o),
    .wbs_dat_i (wb_rgb_led_dat_i),
    .wbs_ack_i (wb_rgb_led_ack_i),
    .wbs_err_i (wb_rgb_led_err_i),
    .wbs_rty_i (wb_rgb_led_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_ps2_0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_ps2_0_adr, wb_m2s_dbg_ps2_0_adr, wb_m2s_dbg_rs232_ps2_0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_ps2_0_dat, wb_m2s_dbg_ps2_0_dat, wb_m2s_dbg_rs232_ps2_0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_ps2_0_sel, wb_m2s_dbg_ps2_0_sel, wb_m2s_dbg_rs232_ps2_0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_ps2_0_we, wb_m2s_dbg_ps2_0_we, wb_m2s_dbg_rs232_ps2_0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_ps2_0_cyc, wb_m2s_dbg_ps2_0_cyc, wb_m2s_dbg_rs232_ps2_0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_ps2_0_stb, wb_m2s_dbg_ps2_0_stb, wb_m2s_dbg_rs232_ps2_0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_ps2_0_cti, wb_m2s_dbg_ps2_0_cti, wb_m2s_dbg_rs232_ps2_0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_ps2_0_bte, wb_m2s_dbg_ps2_0_bte, wb_m2s_dbg_rs232_ps2_0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_ps2_0_dat, wb_s2m_dbg_ps2_0_dat, wb_s2m_dbg_rs232_ps2_0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_ps2_0_ack, wb_s2m_dbg_ps2_0_ack, wb_s2m_dbg_rs232_ps2_0_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_ps2_0_err, wb_s2m_dbg_ps2_0_err, wb_s2m_dbg_rs232_ps2_0_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_ps2_0_rty, wb_s2m_dbg_ps2_0_rty, wb_s2m_dbg_rs232_ps2_0_rty}),
    .wbs_adr_o (wb_m2s_resize_ps2_0_adr),
    .wbs_dat_o (wb_m2s_resize_ps2_0_dat),
    .wbs_sel_o (wb_m2s_resize_ps2_0_sel),
    .wbs_we_o  (wb_m2s_resize_ps2_0_we),
    .wbs_cyc_o (wb_m2s_resize_ps2_0_cyc),
    .wbs_stb_o (wb_m2s_resize_ps2_0_stb),
    .wbs_cti_o (wb_m2s_resize_ps2_0_cti),
    .wbs_bte_o (wb_m2s_resize_ps2_0_bte),
    .wbs_dat_i (wb_s2m_resize_ps2_0_dat),
    .wbs_ack_i (wb_s2m_resize_ps2_0_ack),
    .wbs_err_i (wb_s2m_resize_ps2_0_err),
    .wbs_rty_i (wb_s2m_resize_ps2_0_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_ps2_0
   (.wbm_adr_i (wb_m2s_resize_ps2_0_adr),
    .wbm_dat_i (wb_m2s_resize_ps2_0_dat),
    .wbm_sel_i (wb_m2s_resize_ps2_0_sel),
    .wbm_we_i  (wb_m2s_resize_ps2_0_we),
    .wbm_cyc_i (wb_m2s_resize_ps2_0_cyc),
    .wbm_stb_i (wb_m2s_resize_ps2_0_stb),
    .wbm_cti_i (wb_m2s_resize_ps2_0_cti),
    .wbm_bte_i (wb_m2s_resize_ps2_0_bte),
    .wbm_dat_o (wb_s2m_resize_ps2_0_dat),
    .wbm_ack_o (wb_s2m_resize_ps2_0_ack),
    .wbm_err_o (wb_s2m_resize_ps2_0_err),
    .wbm_rty_o (wb_s2m_resize_ps2_0_rty),
    .wbs_adr_o (wb_ps2_0_adr_o),
    .wbs_dat_o (wb_ps2_0_dat_o),
    .wbs_we_o  (wb_ps2_0_we_o),
    .wbs_cyc_o (wb_ps2_0_cyc_o),
    .wbs_stb_o (wb_ps2_0_stb_o),
    .wbs_cti_o (wb_ps2_0_cti_o),
    .wbs_bte_o (wb_ps2_0_bte_o),
    .wbs_dat_i (wb_ps2_0_dat_i),
    .wbs_ack_i (wb_ps2_0_ack_i),
    .wbs_err_i (wb_ps2_0_err_i),
    .wbs_rty_i (wb_ps2_0_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_xadc0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_xadc0_adr, wb_m2s_dbg_xadc0_adr, wb_m2s_dbg_rs232_xadc0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_xadc0_dat, wb_m2s_dbg_xadc0_dat, wb_m2s_dbg_rs232_xadc0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_xadc0_sel, wb_m2s_dbg_xadc0_sel, wb_m2s_dbg_rs232_xadc0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_xadc0_we, wb_m2s_dbg_xadc0_we, wb_m2s_dbg_rs232_xadc0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_xadc0_cyc, wb_m2s_dbg_xadc0_cyc, wb_m2s_dbg_rs232_xadc0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_xadc0_stb, wb_m2s_dbg_xadc0_stb, wb_m2s_dbg_rs232_xadc0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_xadc0_cti, wb_m2s_dbg_xadc0_cti, wb_m2s_dbg_rs232_xadc0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_xadc0_bte, wb_m2s_dbg_xadc0_bte, wb_m2s_dbg_rs232_xadc0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_xadc0_dat, wb_s2m_dbg_xadc0_dat, wb_s2m_dbg_rs232_xadc0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_xadc0_ack, wb_s2m_dbg_xadc0_ack, wb_s2m_dbg_rs232_xadc0_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_xadc0_err, wb_s2m_dbg_xadc0_err, wb_s2m_dbg_rs232_xadc0_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_xadc0_rty, wb_s2m_dbg_xadc0_rty, wb_s2m_dbg_rs232_xadc0_rty}),
    .wbs_adr_o (wb_m2s_resize_xadc0_adr),
    .wbs_dat_o (wb_m2s_resize_xadc0_dat),
    .wbs_sel_o (wb_m2s_resize_xadc0_sel),
    .wbs_we_o  (wb_m2s_resize_xadc0_we),
    .wbs_cyc_o (wb_m2s_resize_xadc0_cyc),
    .wbs_stb_o (wb_m2s_resize_xadc0_stb),
    .wbs_cti_o (wb_m2s_resize_xadc0_cti),
    .wbs_bte_o (wb_m2s_resize_xadc0_bte),
    .wbs_dat_i (wb_s2m_resize_xadc0_dat),
    .wbs_ack_i (wb_s2m_resize_xadc0_ack),
    .wbs_err_i (wb_s2m_resize_xadc0_err),
    .wbs_rty_i (wb_s2m_resize_xadc0_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (16))
 wb_data_resize_xadc0
   (.wbm_adr_i (wb_m2s_resize_xadc0_adr),
    .wbm_dat_i (wb_m2s_resize_xadc0_dat),
    .wbm_sel_i (wb_m2s_resize_xadc0_sel),
    .wbm_we_i  (wb_m2s_resize_xadc0_we),
    .wbm_cyc_i (wb_m2s_resize_xadc0_cyc),
    .wbm_stb_i (wb_m2s_resize_xadc0_stb),
    .wbm_cti_i (wb_m2s_resize_xadc0_cti),
    .wbm_bte_i (wb_m2s_resize_xadc0_bte),
    .wbm_dat_o (wb_s2m_resize_xadc0_dat),
    .wbm_ack_o (wb_s2m_resize_xadc0_ack),
    .wbm_err_o (wb_s2m_resize_xadc0_err),
    .wbm_rty_o (wb_s2m_resize_xadc0_rty),
    .wbs_adr_o (wb_xadc0_adr_o),
    .wbs_dat_o (wb_xadc0_dat_o),
    .wbs_we_o  (wb_xadc0_we_o),
    .wbs_cyc_o (wb_xadc0_cyc_o),
    .wbs_stb_o (wb_xadc0_stb_o),
    .wbs_cti_o (wb_xadc0_cti_o),
    .wbs_bte_o (wb_xadc0_bte_o),
    .wbs_dat_i (wb_xadc0_dat_i),
    .wbs_ack_i (wb_xadc0_ack_i),
    .wbs_err_i (wb_xadc0_err_i),
    .wbs_rty_i (wb_xadc0_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_ddr2_cfg0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_ddr2_cfg0_adr, wb_m2s_dbg_ddr2_cfg0_adr, wb_m2s_dbg_rs232_ddr2_cfg0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_ddr2_cfg0_dat, wb_m2s_dbg_ddr2_cfg0_dat, wb_m2s_dbg_rs232_ddr2_cfg0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_ddr2_cfg0_sel, wb_m2s_dbg_ddr2_cfg0_sel, wb_m2s_dbg_rs232_ddr2_cfg0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_ddr2_cfg0_we, wb_m2s_dbg_ddr2_cfg0_we, wb_m2s_dbg_rs232_ddr2_cfg0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_ddr2_cfg0_cyc, wb_m2s_dbg_ddr2_cfg0_cyc, wb_m2s_dbg_rs232_ddr2_cfg0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_ddr2_cfg0_stb, wb_m2s_dbg_ddr2_cfg0_stb, wb_m2s_dbg_rs232_ddr2_cfg0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_ddr2_cfg0_cti, wb_m2s_dbg_ddr2_cfg0_cti, wb_m2s_dbg_rs232_ddr2_cfg0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_ddr2_cfg0_bte, wb_m2s_dbg_ddr2_cfg0_bte, wb_m2s_dbg_rs232_ddr2_cfg0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_ddr2_cfg0_dat, wb_s2m_dbg_ddr2_cfg0_dat, wb_s2m_dbg_rs232_ddr2_cfg0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_ddr2_cfg0_ack, wb_s2m_dbg_ddr2_cfg0_ack, wb_s2m_dbg_rs232_ddr2_cfg0_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_ddr2_cfg0_err, wb_s2m_dbg_ddr2_cfg0_err, wb_s2m_dbg_rs232_ddr2_cfg0_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_ddr2_cfg0_rty, wb_s2m_dbg_ddr2_cfg0_rty, wb_s2m_dbg_rs232_ddr2_cfg0_rty}),
    .wbs_adr_o (wb_m2s_resize_ddr2_cfg0_adr),
    .wbs_dat_o (wb_m2s_resize_ddr2_cfg0_dat),
    .wbs_sel_o (wb_m2s_resize_ddr2_cfg0_sel),
    .wbs_we_o  (wb_m2s_resize_ddr2_cfg0_we),
    .wbs_cyc_o (wb_m2s_resize_ddr2_cfg0_cyc),
    .wbs_stb_o (wb_m2s_resize_ddr2_cfg0_stb),
    .wbs_cti_o (wb_m2s_resize_ddr2_cfg0_cti),
    .wbs_bte_o (wb_m2s_resize_ddr2_cfg0_bte),
    .wbs_dat_i (wb_s2m_resize_ddr2_cfg0_dat),
    .wbs_ack_i (wb_s2m_resize_ddr2_cfg0_ack),
    .wbs_err_i (wb_s2m_resize_ddr2_cfg0_err),
    .wbs_rty_i (wb_s2m_resize_ddr2_cfg0_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (16))
 wb_data_resize_ddr2_cfg0
   (.wbm_adr_i (wb_m2s_resize_ddr2_cfg0_adr),
    .wbm_dat_i (wb_m2s_resize_ddr2_cfg0_dat),
    .wbm_sel_i (wb_m2s_resize_ddr2_cfg0_sel),
    .wbm_we_i  (wb_m2s_resize_ddr2_cfg0_we),
    .wbm_cyc_i (wb_m2s_resize_ddr2_cfg0_cyc),
    .wbm_stb_i (wb_m2s_resize_ddr2_cfg0_stb),
    .wbm_cti_i (wb_m2s_resize_ddr2_cfg0_cti),
    .wbm_bte_i (wb_m2s_resize_ddr2_cfg0_bte),
    .wbm_dat_o (wb_s2m_resize_ddr2_cfg0_dat),
    .wbm_ack_o (wb_s2m_resize_ddr2_cfg0_ack),
    .wbm_err_o (wb_s2m_resize_ddr2_cfg0_err),
    .wbm_rty_o (wb_s2m_resize_ddr2_cfg0_rty),
    .wbs_adr_o (wb_ddr2_cfg0_adr_o),
    .wbs_dat_o (wb_ddr2_cfg0_dat_o),
    .wbs_we_o  (wb_ddr2_cfg0_we_o),
    .wbs_cyc_o (wb_ddr2_cfg0_cyc_o),
    .wbs_stb_o (wb_ddr2_cfg0_stb_o),
    .wbs_cti_o (wb_ddr2_cfg0_cti_o),
    .wbs_bte_o (wb_ddr2_cfg0_bte_o),
    .wbs_dat_i (wb_ddr2_cfg0_dat_i),
    .wbs_ack_i (wb_ddr2_cfg0_ack_i),
    .wbs_err_i (wb_ddr2_cfg0_err_i),
    .wbs_rty_i (wb_ddr2_cfg0_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_spi_flash
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_spi_flash_adr, wb_m2s_dbg_spi_flash_adr, wb_m2s_dbg_rs232_spi_flash_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_spi_flash_dat, wb_m2s_dbg_spi_flash_dat, wb_m2s_dbg_rs232_spi_flash_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_spi_flash_sel, wb_m2s_dbg_spi_flash_sel, wb_m2s_dbg_rs232_spi_flash_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_spi_flash_we, wb_m2s_dbg_spi_flash_we, wb_m2s_dbg_rs232_spi_flash_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_spi_flash_cyc, wb_m2s_dbg_spi_flash_cyc, wb_m2s_dbg_rs232_spi_flash_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_spi_flash_stb, wb_m2s_dbg_spi_flash_stb, wb_m2s_dbg_rs232_spi_flash_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_spi_flash_cti, wb_m2s_dbg_spi_flash_cti, wb_m2s_dbg_rs232_spi_flash_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_spi_flash_bte, wb_m2s_dbg_spi_flash_bte, wb_m2s_dbg_rs232_spi_flash_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_spi_flash_dat, wb_s2m_dbg_spi_flash_dat, wb_s2m_dbg_rs232_spi_flash_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_spi_flash_ack, wb_s2m_dbg_spi_flash_ack, wb_s2m_dbg_rs232_spi_flash_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_spi_flash_err, wb_s2m_dbg_spi_flash_err, wb_s2m_dbg_rs232_spi_flash_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_spi_flash_rty, wb_s2m_dbg_spi_flash_rty, wb_s2m_dbg_rs232_spi_flash_rty}),
    .wbs_adr_o (wb_m2s_resize_spi_flash_adr),
    .wbs_dat_o (wb_m2s_resize_spi_flash_dat),
    .wbs_sel_o (wb_m2s_resize_spi_flash_sel),
    .wbs_we_o  (wb_m2s_resize_spi_flash_we),
    .wbs_cyc_o (wb_m2s_resize_spi_flash_cyc),
    .wbs_stb_o (wb_m2s_resize_spi_flash_stb),
    .wbs_cti_o (wb_m2s_resize_spi_flash_cti),
    .wbs_bte_o (wb_m2s_resize_spi_flash_bte),
    .wbs_dat_i (wb_s2m_resize_spi_flash_dat),
    .wbs_ack_i (wb_s2m_resize_spi_flash_ack),
    .wbs_err_i (wb_s2m_resize_spi_flash_err),
    .wbs_rty_i (wb_s2m_resize_spi_flash_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_spi_flash
   (.wbm_adr_i (wb_m2s_resize_spi_flash_adr),
    .wbm_dat_i (wb_m2s_resize_spi_flash_dat),
    .wbm_sel_i (wb_m2s_resize_spi_flash_sel),
    .wbm_we_i  (wb_m2s_resize_spi_flash_we),
    .wbm_cyc_i (wb_m2s_resize_spi_flash_cyc),
    .wbm_stb_i (wb_m2s_resize_spi_flash_stb),
    .wbm_cti_i (wb_m2s_resize_spi_flash_cti),
    .wbm_bte_i (wb_m2s_resize_spi_flash_bte),
    .wbm_dat_o (wb_s2m_resize_spi_flash_dat),
    .wbm_ack_o (wb_s2m_resize_spi_flash_ack),
    .wbm_err_o (wb_s2m_resize_spi_flash_err),
    .wbm_rty_o (wb_s2m_resize_spi_flash_rty),
    .wbs_adr_o (wb_spi_flash_adr_o),
    .wbs_dat_o (wb_spi_flash_dat_o),
    .wbs_we_o  (wb_spi_flash_we_o),
    .wbs_cyc_o (wb_spi_flash_cyc_o),
    .wbs_stb_o (wb_spi_flash_stb_o),
    .wbs_cti_o (wb_spi_flash_cti_o),
    .wbs_bte_o (wb_spi_flash_bte_o),
    .wbs_dat_i (wb_spi_flash_dat_i),
    .wbs_ack_i (wb_spi_flash_ack_i),
    .wbs_err_i (wb_spi_flash_err_i),
    .wbs_rty_i (wb_spi_flash_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_spi_accel
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_spi_accel_adr, wb_m2s_dbg_spi_accel_adr, wb_m2s_dbg_rs232_spi_accel_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_spi_accel_dat, wb_m2s_dbg_spi_accel_dat, wb_m2s_dbg_rs232_spi_accel_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_spi_accel_sel, wb_m2s_dbg_spi_accel_sel, wb_m2s_dbg_rs232_spi_accel_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_spi_accel_we, wb_m2s_dbg_spi_accel_we, wb_m2s_dbg_rs232_spi_accel_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_spi_accel_cyc, wb_m2s_dbg_spi_accel_cyc, wb_m2s_dbg_rs232_spi_accel_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_spi_accel_stb, wb_m2s_dbg_spi_accel_stb, wb_m2s_dbg_rs232_spi_accel_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_spi_accel_cti, wb_m2s_dbg_spi_accel_cti, wb_m2s_dbg_rs232_spi_accel_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_spi_accel_bte, wb_m2s_dbg_spi_accel_bte, wb_m2s_dbg_rs232_spi_accel_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_spi_accel_dat, wb_s2m_dbg_spi_accel_dat, wb_s2m_dbg_rs232_spi_accel_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_spi_accel_ack, wb_s2m_dbg_spi_accel_ack, wb_s2m_dbg_rs232_spi_accel_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_spi_accel_err, wb_s2m_dbg_spi_accel_err, wb_s2m_dbg_rs232_spi_accel_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_spi_accel_rty, wb_s2m_dbg_spi_accel_rty, wb_s2m_dbg_rs232_spi_accel_rty}),
    .wbs_adr_o (wb_m2s_resize_spi_accel_adr),
    .wbs_dat_o (wb_m2s_resize_spi_accel_dat),
    .wbs_sel_o (wb_m2s_resize_spi_accel_sel),
    .wbs_we_o  (wb_m2s_resize_spi_accel_we),
    .wbs_cyc_o (wb_m2s_resize_spi_accel_cyc),
    .wbs_stb_o (wb_m2s_resize_spi_accel_stb),
    .wbs_cti_o (wb_m2s_resize_spi_accel_cti),
    .wbs_bte_o (wb_m2s_resize_spi_accel_bte),
    .wbs_dat_i (wb_s2m_resize_spi_accel_dat),
    .wbs_ack_i (wb_s2m_resize_spi_accel_ack),
    .wbs_err_i (wb_s2m_resize_spi_accel_err),
    .wbs_rty_i (wb_s2m_resize_spi_accel_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_spi_accel
   (.wbm_adr_i (wb_m2s_resize_spi_accel_adr),
    .wbm_dat_i (wb_m2s_resize_spi_accel_dat),
    .wbm_sel_i (wb_m2s_resize_spi_accel_sel),
    .wbm_we_i  (wb_m2s_resize_spi_accel_we),
    .wbm_cyc_i (wb_m2s_resize_spi_accel_cyc),
    .wbm_stb_i (wb_m2s_resize_spi_accel_stb),
    .wbm_cti_i (wb_m2s_resize_spi_accel_cti),
    .wbm_bte_i (wb_m2s_resize_spi_accel_bte),
    .wbm_dat_o (wb_s2m_resize_spi_accel_dat),
    .wbm_ack_o (wb_s2m_resize_spi_accel_ack),
    .wbm_err_o (wb_s2m_resize_spi_accel_err),
    .wbm_rty_o (wb_s2m_resize_spi_accel_rty),
    .wbs_adr_o (wb_spi_accel_adr_o),
    .wbs_dat_o (wb_spi_accel_dat_o),
    .wbs_we_o  (wb_spi_accel_we_o),
    .wbs_cyc_o (wb_spi_accel_cyc_o),
    .wbs_stb_o (wb_spi_accel_stb_o),
    .wbs_cti_o (wb_spi_accel_cti_o),
    .wbs_bte_o (wb_spi_accel_bte_o),
    .wbs_dat_i (wb_spi_accel_dat_i),
    .wbs_ack_i (wb_spi_accel_ack_i),
    .wbs_err_i (wb_spi_accel_err_i),
    .wbs_rty_i (wb_spi_accel_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_i2c_temp
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_d_i2c_temp_adr, wb_m2s_dbg_i2c_temp_adr, wb_m2s_dbg_rs232_i2c_temp_adr}),
    .wbm_dat_i ({wb_m2s_or1k_d_i2c_temp_dat, wb_m2s_dbg_i2c_temp_dat, wb_m2s_dbg_rs232_i2c_temp_dat}),
    .wbm_sel_i ({wb_m2s_or1k_d_i2c_temp_sel, wb_m2s_dbg_i2c_temp_sel, wb_m2s_dbg_rs232_i2c_temp_sel}),
    .wbm_we_i  ({wb_m2s_or1k_d_i2c_temp_we, wb_m2s_dbg_i2c_temp_we, wb_m2s_dbg_rs232_i2c_temp_we}),
    .wbm_cyc_i ({wb_m2s_or1k_d_i2c_temp_cyc, wb_m2s_dbg_i2c_temp_cyc, wb_m2s_dbg_rs232_i2c_temp_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_d_i2c_temp_stb, wb_m2s_dbg_i2c_temp_stb, wb_m2s_dbg_rs232_i2c_temp_stb}),
    .wbm_cti_i ({wb_m2s_or1k_d_i2c_temp_cti, wb_m2s_dbg_i2c_temp_cti, wb_m2s_dbg_rs232_i2c_temp_cti}),
    .wbm_bte_i ({wb_m2s_or1k_d_i2c_temp_bte, wb_m2s_dbg_i2c_temp_bte, wb_m2s_dbg_rs232_i2c_temp_bte}),
    .wbm_dat_o ({wb_s2m_or1k_d_i2c_temp_dat, wb_s2m_dbg_i2c_temp_dat, wb_s2m_dbg_rs232_i2c_temp_dat}),
    .wbm_ack_o ({wb_s2m_or1k_d_i2c_temp_ack, wb_s2m_dbg_i2c_temp_ack, wb_s2m_dbg_rs232_i2c_temp_ack}),
    .wbm_err_o ({wb_s2m_or1k_d_i2c_temp_err, wb_s2m_dbg_i2c_temp_err, wb_s2m_dbg_rs232_i2c_temp_err}),
    .wbm_rty_o ({wb_s2m_or1k_d_i2c_temp_rty, wb_s2m_dbg_i2c_temp_rty, wb_s2m_dbg_rs232_i2c_temp_rty}),
    .wbs_adr_o (wb_m2s_resize_i2c_temp_adr),
    .wbs_dat_o (wb_m2s_resize_i2c_temp_dat),
    .wbs_sel_o (wb_m2s_resize_i2c_temp_sel),
    .wbs_we_o  (wb_m2s_resize_i2c_temp_we),
    .wbs_cyc_o (wb_m2s_resize_i2c_temp_cyc),
    .wbs_stb_o (wb_m2s_resize_i2c_temp_stb),
    .wbs_cti_o (wb_m2s_resize_i2c_temp_cti),
    .wbs_bte_o (wb_m2s_resize_i2c_temp_bte),
    .wbs_dat_i (wb_s2m_resize_i2c_temp_dat),
    .wbs_ack_i (wb_s2m_resize_i2c_temp_ack),
    .wbs_err_i (wb_s2m_resize_i2c_temp_err),
    .wbs_rty_i (wb_s2m_resize_i2c_temp_rty));

wb_data_resize
  #(.aw  (32),
    .mdw (32),
    .sdw (8))
 wb_data_resize_i2c_temp
   (.wbm_adr_i (wb_m2s_resize_i2c_temp_adr),
    .wbm_dat_i (wb_m2s_resize_i2c_temp_dat),
    .wbm_sel_i (wb_m2s_resize_i2c_temp_sel),
    .wbm_we_i  (wb_m2s_resize_i2c_temp_we),
    .wbm_cyc_i (wb_m2s_resize_i2c_temp_cyc),
    .wbm_stb_i (wb_m2s_resize_i2c_temp_stb),
    .wbm_cti_i (wb_m2s_resize_i2c_temp_cti),
    .wbm_bte_i (wb_m2s_resize_i2c_temp_bte),
    .wbm_dat_o (wb_s2m_resize_i2c_temp_dat),
    .wbm_ack_o (wb_s2m_resize_i2c_temp_ack),
    .wbm_err_o (wb_s2m_resize_i2c_temp_err),
    .wbm_rty_o (wb_s2m_resize_i2c_temp_rty),
    .wbs_adr_o (wb_i2c_temp_adr_o),
    .wbs_dat_o (wb_i2c_temp_dat_o),
    .wbs_we_o  (wb_i2c_temp_we_o),
    .wbs_cyc_o (wb_i2c_temp_cyc_o),
    .wbs_stb_o (wb_i2c_temp_stb_o),
    .wbs_cti_o (wb_i2c_temp_cti_o),
    .wbs_bte_o (wb_i2c_temp_bte_o),
    .wbs_dat_i (wb_i2c_temp_dat_i),
    .wbs_ack_i (wb_i2c_temp_ack_i),
    .wbs_err_i (wb_i2c_temp_err_i),
    .wbs_rty_i (wb_i2c_temp_rty_i));

wb_arbiter
  #(.num_masters (3))
 wb_arbiter_rom0
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i ({wb_m2s_or1k_i_rom0_adr, wb_m2s_dbg_rom0_adr, wb_m2s_dbg_rs232_rom0_adr}),
    .wbm_dat_i ({wb_m2s_or1k_i_rom0_dat, wb_m2s_dbg_rom0_dat, wb_m2s_dbg_rs232_rom0_dat}),
    .wbm_sel_i ({wb_m2s_or1k_i_rom0_sel, wb_m2s_dbg_rom0_sel, wb_m2s_dbg_rs232_rom0_sel}),
    .wbm_we_i  ({wb_m2s_or1k_i_rom0_we, wb_m2s_dbg_rom0_we, wb_m2s_dbg_rs232_rom0_we}),
    .wbm_cyc_i ({wb_m2s_or1k_i_rom0_cyc, wb_m2s_dbg_rom0_cyc, wb_m2s_dbg_rs232_rom0_cyc}),
    .wbm_stb_i ({wb_m2s_or1k_i_rom0_stb, wb_m2s_dbg_rom0_stb, wb_m2s_dbg_rs232_rom0_stb}),
    .wbm_cti_i ({wb_m2s_or1k_i_rom0_cti, wb_m2s_dbg_rom0_cti, wb_m2s_dbg_rs232_rom0_cti}),
    .wbm_bte_i ({wb_m2s_or1k_i_rom0_bte, wb_m2s_dbg_rom0_bte, wb_m2s_dbg_rs232_rom0_bte}),
    .wbm_dat_o ({wb_s2m_or1k_i_rom0_dat, wb_s2m_dbg_rom0_dat, wb_s2m_dbg_rs232_rom0_dat}),
    .wbm_ack_o ({wb_s2m_or1k_i_rom0_ack, wb_s2m_dbg_rom0_ack, wb_s2m_dbg_rs232_rom0_ack}),
    .wbm_err_o ({wb_s2m_or1k_i_rom0_err, wb_s2m_dbg_rom0_err, wb_s2m_dbg_rs232_rom0_err}),
    .wbm_rty_o ({wb_s2m_or1k_i_rom0_rty, wb_s2m_dbg_rom0_rty, wb_s2m_dbg_rs232_rom0_rty}),
    .wbs_adr_o (wb_rom0_adr_o),
    .wbs_dat_o (wb_rom0_dat_o),
    .wbs_sel_o (wb_rom0_sel_o),
    .wbs_we_o  (wb_rom0_we_o),
    .wbs_cyc_o (wb_rom0_cyc_o),
    .wbs_stb_o (wb_rom0_stb_o),
    .wbs_cti_o (wb_rom0_cti_o),
    .wbs_bte_o (wb_rom0_bte_o),
    .wbs_dat_i (wb_rom0_dat_i),
    .wbs_ack_i (wb_rom0_ack_i),
    .wbs_err_i (wb_rom0_err_i),
    .wbs_rty_i (wb_rom0_rty_i));

endmodule
