#!/bin/sh

echo Debugging $1

or1k-elf-gdb $1 --eval-command='target remote :3333' --eval-command='set remotetimeout unlimited' --eval-command='load' --eval-command='break *0x100' --eval-command='jump *0x100'